# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)

1.26.4


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
a = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [6]:
a.nbytes
answer(4)

Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
# help(np.add)
answer(5)

%run `python -c "import numpy; numpy.info(numpy.add)"`


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [9]:
answer(6)

Z = np.zeros(10)
Z[4] = 1
print(Z)


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
a = np.random.randint(10, 50, 10)
a


array([20, 21, 13, 23, 28, 10, 10, 34, 40, 44])

In [11]:
answer(7)

Z = np.arange(10,50)
print(Z)


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [12]:
a[::-1]

array([44, 40, 34, 10, 10, 28, 23, 13, 21, 20])

In [13]:
answer(8)

Z = np.arange(50)
Z = Z[::-1]
print(Z)


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [14]:
a = np.random.randint(0, 9, 9).reshape(3, 3)
a

array([[3, 2, 7],
       [7, 0, 3],
       [8, 4, 8]])

In [15]:
answer(9)

Z = np.arange(9).reshape(3, 3)
print(Z)


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [16]:
a = np.array([1, 2, 0, 0, 4, 0])
a = np.where(a == 0)
a

(array([2, 3, 5], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [17]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [18]:
np.random.random([3, 3, 3])

array([[[0.68581973, 0.0609303 , 0.2280511 ],
        [0.55493794, 0.34988963, 0.2024133 ],
        [0.67878015, 0.05874385, 0.32101942]],

       [[0.52677954, 0.93490112, 0.08192652],
        [0.76295431, 0.49330188, 0.53176016],
        [0.70982949, 0.2951781 , 0.91277937]],

       [[0.65935005, 0.46985547, 0.21950293],
        [0.07083616, 0.9270269 , 0.46116926],
        [0.14811286, 0.8141783 , 0.92289996]]])

In [19]:
answer(12)

Z = np.random.random((3,3,3))
print(Z)


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [20]:
a = np.random.random([10, 10])
print(a.min(), a.max())

0.006879604655824156 0.9915516964280421


In [21]:
answer(13)

Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [22]:
a = np.random.random(30).mean()
print(a)

0.40496487488534466


In [23]:
answer(14)

Z = np.random.random(30)
m = Z.mean()
print(m)


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [24]:
a = np.ones([4, 4])
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [25]:
answer(15)

Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [26]:
a = np.ones([3, 3])
a = np.pad(a, pad_width=1, mode="constant")  # padding
a

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
answer(16)

Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [28]:
0.3 == 3 * 0.1

False

In [29]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [30]:
answer(17)

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [31]:
np.diag([1, 2, 3, 4], k=0)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [32]:
a = np.zeros([8, 8])
a[::2, ::2] = 1
a[1::2, 1::2] = 1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [33]:
a = np.array(np.arange(336).reshape(6, 7, 8))
a[1, 5, 3]

99

In [34]:
print(np.unravel_index(99,(6,7,8)))  # 1次元のインデックスを多次元インデックスに変換してくれる

(1, 5, 3)


In [35]:
answer(20)

print(np.unravel_index(99,(6,7,8)))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [36]:
a = [[0, 1], [1, 0]]
b = np.tile(a, (4, 4))
b

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [37]:
answer(21)

Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [38]:
a = np.array(np.random.random((5, 5)))
a_min = a.min()
a_max = a.max()
a = (a - a_min) / (a_max - a_min)
a


array([[0.70329591, 0.15207978, 0.04613405, 0.4555045 , 0.87152981],
       [1.        , 0.9266431 , 0.818093  , 0.82776251, 0.85804786],
       [0.92910249, 0.64135666, 0.90705933, 0.        , 0.90556228],
       [0.24682631, 0.41687106, 0.68043223, 0.71723076, 0.8915366 ],
       [0.57535629, 0.92257051, 0.97529337, 0.49521628, 0.65883075]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [39]:
color = np.dtype([("r", np.ubyte),
                 ("g", np.ubyte),
                 ("b", np.ubyte),
                 ("a", np.ubyte)])

In [40]:
answer(23)

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [41]:
a = np.array(np.random.random([5, 3]))
b = np.array(np.random.random([3, 2]))
np.matmul(a, b)

array([[0.21489046, 0.41249664],
       [0.660015  , 0.99919723],
       [0.42918267, 0.73842199],
       [0.52883243, 1.22266758],
       [0.35216242, 0.87293342]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [42]:
a = np.array(np.arange(11))
a[((3 < a) & (a < 8))] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

In [43]:
answer(25)

# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)


In [44]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [45]:
sum(range(5), -1)

9

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [46]:
####
"""python
1. ok
2. no
3. ok
4. ok
5. ok
6. no
"""

'python\n1. ok\n2. no\n3. ok\n4. ok\n5. ok\n6. no\n'

In [47]:
Z = np.array([1, 2, 3])
1j*Z  # jは虚数単位

array([0.+1.j, 0.+2.j, 0.+3.j])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [48]:
np.array(0) / np.array(0)  # numpyはエラーが出たときに中断せずに、nanを返す

C:\Users\CHU1P\AppData\Local\Temp\ipykernel_10928\941235769.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)  # numpyはエラーが出たときに中断せずに、nanを返す


nan

In [49]:
np.array(0) // np.array(0)

C:\Users\CHU1P\AppData\Local\Temp\ipykernel_10928\2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [50]:
np.array([np.nan]).astype(int).astype(float)  # np.nanはint型に変えるとその方の最小値になる

C:\Users\CHU1P\AppData\Local\Temp\ipykernel_10928\2424127791.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)  # np.nanはint型に変えるとその方の最小値になる


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [51]:
a = np.array(np.random.uniform(-10, 10, 5))
print(a)
a = np.where(a >= 0, np.ceil(a), np.floor(a))
print(a)

[-7.02140885  9.18675558 -2.88783367  3.28387794  8.24014972]
[-8. 10. -3.  4.  9.]


In [52]:
answer(29)

# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))


#### 30. How to find common values between two arrays? (★☆☆)

In [53]:
a = np.random.randint(1, 9, 5)
b = np.random.randint(1, 9, 5)
print(a, b)
np.intersect1d(a, b)  # 共通の値を出力する, 出力はsortされている

[8 1 5 1 7] [4 2 5 3 8]


array([5, 8])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [54]:
answer(31)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


In [55]:
defaults = np.seterr(all="ignore")
z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [56]:
np.emath.sqrt(-1)  # emathは複素数が答えの場合は複素数に変える

1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [57]:
print(np.datetime64("today", "D") - np.timedelta64(1, "D"))
print(np.datetime64("today", "D"))
print(np.datetime64("today", "D") + np.timedelta64(1, "D"))

2025-06-22
2025-06-23
2025-06-24


In [58]:
import pandas as pd

today = pd.Timestamp("today")
yesterday = (today - pd.Timedelta(days=1)).strftime("%Y-%m-%d")
tomorrow = (today + pd.Timedelta(days=1)).strftime("%Y-%m-%d")
today = today.strftime("%Y-%m-%d")
print(yesterday, today, tomorrow)

2025-06-22 2025-06-23 2025-06-24


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [59]:
a = pd.date_range(start="2016-07-01", end="2016-07-31", freq="D")
a

DatetimeIndex(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
               '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
               '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
               '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
               '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
               '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
               '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
               '2016-07-29', '2016-07-30', '2016-07-31'],
              dtype='datetime64[ns]', freq='D')

In [60]:
np.arange("2016-07", "2016-08", dtype="datetime64[D]")

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [61]:
answer(34)

Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [62]:
answer(35)

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


In [63]:
A = np.ones(3) * 1
B = np.ones(3) * 2
print(B)
print(np.add(A, B, out=B))  # numpyのaddやnegativeを使うことによってメモリの使用を削減できる
np.negative(A, out=A)
print(np.divide(A, 2, out=A))

[2. 2. 2.]
[3. 3. 3.]
[-0.5 -0.5 -0.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [64]:
a = np.array([9.43702508, 5.44392995, -8.80030341, -4.46399976, -1.06240269])
print(a.astype(int))
print(np.where(a >= 0, np.floor(a), np.ceil(a)))
print(a // 1)
print(np.trunc(a))  # np.where(a >= 0, np.floor(a), np.ceil(a))これと同じ

[ 9  5 -8 -4 -1]
[ 9.  5. -8. -4. -1.]
[ 9.  5. -9. -5. -2.]
[ 9.  5. -8. -4. -1.]


In [65]:
answer(36)

Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [66]:
np.array(np.tile([0, 1, 2, 3, 4], (5, 1)))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [67]:
answer(37)

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [68]:
def int_generator():
    for i in range(10):
        yield i

print(np.fromiter(int_generator(), dtype=int))

[0 1 2 3 4 5 6 7 8 9]


In [69]:
answer(38)

def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [70]:
np.nextafter(0, 1)

5e-324

In [71]:
np.random.uniform(np.nextafter(0, 1), 1, 10)

array([0.51798197, 0.88634363, 0.19025783, 0.7989563 , 0.49957988,
       0.35108983, 0.83941084, 0.47233259, 0.53533266, 0.78227964])

In [72]:
np.linspace(0, 1, 11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [73]:
answer(39)

Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [74]:
a = np.random.random(10)
a.sort()
print(a)

[0.06263119 0.06391855 0.30658304 0.41323126 0.67604094 0.68131096
 0.80500074 0.852892   0.86838702 0.97629425]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [75]:
answer(41)

# Author: Evgeni Burovski

Z = np.arange(10)
np.add.reduce(Z)


In [76]:
a = np.arange(10)
np.add.reduce(a)

45

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [77]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
equal = np.allclose(A, B)
print(equal)

False


In [78]:
answer(42)

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)


#### 43. Make an array immutable (read-only) (★★☆)

In [79]:
a = np.array([1, 2, 3])
a.flags.writeable = False
a

array([1, 2, 3])

In [80]:
answer(43)

Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [81]:
A = np.array([[0.16702026, 0.17824744],
 [0.66112783, 0.93869856],
 [0.67644807, 0.3256588 ],
 [0.24854642, 0.58445634],
 [0.0551434, 0.4596011 ],
 [0.49144912, 0.17056799],
 [0.86365082, 0.42253366],
 [0.49300285, 0.74969368],
 [0.5517937, 0.35342211],
 [0.33419615, 0.939642]])
sheta = np.arctan2(A[:, 1] ,A[:, 0])
np.square(A, out=A)
A = np.sum(A, axis=1)
R = np.sqrt(A)
print(R)
print(sheta)


[0.24427017 1.14814851 0.75075672 0.63510986 0.46289736 0.52020734
 0.96147149 0.89726943 0.65527359 0.99730344]
[0.81790403 0.95718855 0.44867724 1.16870473 1.45138613 0.33406354
 0.45500367 0.98909295 0.56966557 1.22908521]


In [82]:
Z = np.random.random((10,2))
print(Z)
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[[0.7229151  0.33358589]
 [0.07922624 0.78374491]
 [0.41686234 0.54463879]
 [0.39203691 0.22215201]
 [0.63996871 0.8970161 ]
 [0.16144713 0.34746775]
 [0.29214226 0.27826817]
 [0.40017535 0.95022741]
 [0.95297623 0.5435612 ]
 [0.55724907 0.27159057]]
[0.79616945 0.7877391  0.68586123 0.45060455 1.10190646 0.38314359
 0.40346038 1.03105404 1.0970973  0.61990964]
[0.4323311  1.47005179 0.91751671 0.51554469 0.95110593 1.13583537
 0.76107998 1.17220273 0.51835737 0.45349859]


In [83]:
answer(44)

Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [84]:
a = np.random.random(10)
a[a.argmax()] = 0
a

array([0.        , 0.17077064, 0.04688524, 0.68913146, 0.62202078,
       0.11673064, 0.61051204, 0.05517234, 0.50407755, 0.19303864])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [85]:
structed_dtype = np.dtype([("x", float), ("y", float)])
a = np.array(np.random.uniform(0, np.nextafter(1, 2), 10).reshape(-1, 2))
a.dtype = structed_dtype
a

array([[(0.26834415, 0.91131907)],
       [(0.84608315, 0.08459469)],
       [(0.6148893 , 0.75639401)],
       [(0.87068575, 0.27000856)],
       [(0.26561033, 0.02928182)]], dtype=[('x', '<f8'), ('y', '<f8')])

In [86]:
answer(46)

Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [87]:
X = np.array(np.random.random(5))
Y = np.array(np.random.random(5))
C = 1 / np.subtract.outer(X, Y)
print(C)

[[ -2.40782369   9.12576077   4.41520514  -5.02410906   6.626184  ]
 [ -1.78369717 -27.97940192  12.31988951  -2.90393143 178.70093285]
 [  5.80871379   1.43462173   1.22856463   2.57448177   1.35430818]
 [ 14.21858797   1.6800421    1.40423145   3.48914692   1.57094457]
 [ -1.83623178 -50.75922668  10.28708312  -3.04579949  46.21997332]]


In [88]:
answer(47)

# Author: Evgeni Burovski

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))


In [89]:
a = np.array(np.random.randint(1, 10, 10))
b = np.array(np.random.randint(1, 10, 3))
np.add.outer(a, b)

array([[ 8,  6,  5],
       [12, 10,  9],
       [ 7,  5,  4],
       [12, 10,  9],
       [ 9,  7,  6],
       [ 8,  6,  5],
       [ 8,  6,  5],
       [ 7,  5,  4],
       [ 8,  6,  5],
       [ 8,  6,  5]])

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [90]:
print(np.iinfo(np.int8))
print(np.finfo(np.float16))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for float16
---------------------------------------------------------------
precision =   3   resolution = 1.00040e-03
machep =    -10   eps =        9.76562e-04
negep =     -11   epsneg =     4.88281e-04
minexp =    -14   tiny =       6.10352e-05
maxexp =     16   max =        6.55040e+04
nexp =        5   min =        -max
smallest_normal = 6.10352e-05   smallest_subnormal = 5.96046e-08
---------------------------------------------------------------



In [91]:
hint(48)

hint: np.iinfo, np.finfo, eps


#### 49. How to print all the values of an array? (★★☆)

In [92]:
np.set_printoptions(threshold=float("inf"))
# np.set_printoptions(threshold=1000)
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [93]:
hint(49)

hint: np.set_printoptions


In [94]:
answer(49)

np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [95]:
a = np.arange(100)
v = np.random.uniform(0, 100)
index = np.abs(np.subtract(a, v)).argmin()
a[index]

37

In [96]:
answer(50)

Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [97]:
a = np.zeros(2, dtype=[("position", [("x", float, 1),
                                      ("y", float, 1)]),
                        ("color", [("r", float, 1),
                                   ("g", float, 1),
                                   ("b", float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\CHU1P\AppData\Local\Temp\ipykernel_10928\4134159954.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = np.zeros(2, dtype=[("position", [("x", float, 1),


In [98]:
answer(51)

Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [99]:
a = np.random.random((10,2))
delta_coords = a[:, np.newaxis, :] - a[np.newaxis, :, :]
r = np.sqrt(np.sum(np.square(delta_coords), axis=2))
print(r[:5])

[[0.         0.75054652 0.60031359 0.22790941 0.11767736 0.100837
  0.5715208  0.59199567 0.38463825 0.26730288]
 [0.75054652 0.         0.25220521 0.84561449 0.76545824 0.71532655
  0.38717073 0.89503894 1.00486668 0.79048901]
 [0.60031359 0.25220521 0.         0.752724   0.58207469 0.59694289
  0.47497298 0.64379571 0.92419124 0.57319596]
 [0.22790941 0.84561449 0.752724   0.         0.34096652 0.16568474
  0.56399583 0.81756078 0.17290881 0.49069024]
 [0.11767736 0.76545824 0.58207469 0.34096652 0.         0.21478917
  0.64357862 0.47660103 0.48669236 0.15020399]]


In [100]:
a[:, np.newaxis, :] - a[np.newaxis, :, :]

array([[[ 0.00000000e+00,  0.00000000e+00],
        [-5.76290315e-01,  4.80842546e-01],
        [-5.54686038e-01,  2.29564370e-01],
        [ 1.90710208e-01,  1.24789089e-01],
        [-7.08180806e-02, -9.39827628e-02],
        [ 2.73634652e-02,  9.70532903e-02],
        [-1.93335989e-01,  5.37826387e-01],
        [-4.33843716e-01, -4.02788416e-01],
        [ 3.63617889e-01,  1.25413778e-01],
        [-1.76260199e-01, -2.00955651e-01]],

       [[ 5.76290315e-01, -4.80842546e-01],
        [ 0.00000000e+00,  0.00000000e+00],
        [ 2.16042772e-02, -2.51278175e-01],
        [ 7.67000523e-01, -3.56053457e-01],
        [ 5.05472235e-01, -5.74825308e-01],
        [ 6.03653780e-01, -3.83789255e-01],
        [ 3.82954326e-01,  5.69838418e-02],
        [ 1.42446599e-01, -8.83630962e-01],
        [ 9.39908205e-01, -3.55428768e-01],
        [ 4.00030116e-01, -6.81798197e-01]],

       [[ 5.54686038e-01, -2.29564370e-01],
        [-2.16042772e-02,  2.51278175e-01],
        [ 0.00000000e+00,  0

In [101]:
Z = np.random.random((10,2))
X,Y = Z[:, np.newaxis, 0], Z[:, np.newaxis, 1]
D = np.sqrt((X - X.T)**2 + (Y - Y.T)**2)
print(D)

[[0.         0.09849958 0.54913486 0.51052639 0.48502786 0.89039087
  0.83340349 0.85360737 0.9308715  0.27925682]
 [0.09849958 0.         0.62931314 0.4954949  0.42677594 0.89318327
  0.81079718 0.92228847 0.98860184 0.35175211]
 [0.54913486 0.62931314 0.         0.57721785 0.7496408  0.71262429
  0.80998566 0.32582268 0.44334261 0.27953256]
 [0.51052639 0.4954949  0.57721785 0.         0.23216104 0.4082949
  0.32393535 0.70999992 0.69864217 0.41950136]
 [0.48502786 0.42677594 0.7496408  0.23216104 0.         0.60179523
  0.44073438 0.92887388 0.92813298 0.52507396]
 [0.89039087 0.89318327 0.71262429 0.4082949  0.60179523 0.
  0.2326439  0.64612068 0.5490712  0.70992153]
 [0.83340349 0.81079718 0.80998566 0.32393535 0.44073438 0.2326439
  0.         0.82414244 0.75150235 0.72290432]
 [0.85360737 0.92228847 0.32582268 0.70999992 0.92887388 0.64612068
  0.82414244 0.         0.15203257 0.57440782]
 [0.9308715  0.98860184 0.44334261 0.69864217 0.92813298 0.5490712
  0.75150235 0.15203257

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [110]:
A = np.random.randn(10)
print(A)
# A[:]とすることでAの要素だけを書き換えれる
A[:] = A.astype(np.int32)
print(A)

[ 0.45776101  0.2636735   1.55215014 -0.50917451  0.20611157 -0.66262539
 -1.49513612 -0.02004416  0.35038805 -1.19287254]
[ 0.  0.  1.  0.  0.  0. -1.  0.  0. -1.]


In [107]:
answer(53)

# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [111]:
hint(54)

hint: np.genfromtxt


In [116]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5
             6, , , 7, 8
              , , 9,10,11""")
data = np.genfromtxt(s, delimiter=",", dtype=float)
data


array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

In [128]:
from io import StringIO
import pandas as pd

s = StringIO("""1, 2, 3, 4, 5
6, , , 7, 8
 , , 9,10,11""")
data = pd.read_csv(s, sep=",", header=None, na_values=[" "])
print(data)

     0    1    2   3   4
0  1.0  2.0  3.0   4   5
1  6.0  NaN  NaN   7   8
2  NaN  NaN  9.0  10  11


In [114]:
answer(54)

from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [129]:
A = np.array([[1, 2], [3, 4]])
for idx, val in np.ndenumerate(A):
    print(idx, val)


(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [130]:
hint(56)

hint: np.meshgrid, np.exp


In [131]:
answer(56)

X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)


In [137]:
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
D = np.sqrt(X*X + Y*Y)
sigma, mu = 1.0, 0.0
y = (np.exp(-(D - mu) / (2 * sigma)) ** 2)
print(y)

[[0.24311673 0.28171437 0.31855539 0.34850854 0.3656225  0.3656225
  0.34850854 0.31855539 0.28171437 0.24311673]
 [0.28171437 0.33288976 0.38449907 0.42904348 0.45581229 0.45581229
  0.42904348 0.38449907 0.33288976 0.28171437]
 [0.31855539 0.38449907 0.45581229 0.52315183 0.56747549 0.56747549
  0.52315183 0.45581229 0.38449907 0.31855539]
 [0.34850854 0.42904348 0.52315183 0.62412506 0.70372742 0.70372742
  0.62412506 0.52315183 0.42904348 0.34850854]
 [0.3656225  0.45581229 0.56747549 0.70372742 0.85458882 0.85458882
  0.70372742 0.56747549 0.45581229 0.3656225 ]
 [0.3656225  0.45581229 0.56747549 0.70372742 0.85458882 0.85458882
  0.70372742 0.56747549 0.45581229 0.3656225 ]
 [0.34850854 0.42904348 0.52315183 0.62412506 0.70372742 0.70372742
  0.62412506 0.52315183 0.42904348 0.34850854]
 [0.31855539 0.38449907 0.45581229 0.52315183 0.56747549 0.56747549
  0.52315183 0.45581229 0.38449907 0.31855539]
 [0.28171437 0.33288976 0.38449907 0.42904348 0.45581229 0.45581229
  0.42904348 

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
A = np.zeros((5, 5))
p = 3
idx = np.unravel_index(np.random.randint(0, 25, p, ), (5, 5))
A[idx] = 1
print(A)

[[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [148]:
A = np.zeros((5, 5))
# choiceが重複のない選択をできる
np.put(A, np.random.choice(25, p, replace=False), 1)
print(A)

[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [143]:
answer(57)

# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
A = np.random.randint(0, 10, (10, 5)).astype(np.float64)
# keepdimsをしないとテンソルとして残らないため
A[:] -= np.mean(A, axis=1, keepdims=True)
print(A)

(10, 1)
[[-0.2  3.8 -2.2  0.8 -2.2]
 [ 0.   1.  -2.   4.  -3. ]
 [-3.   1.  -1.   2.   1. ]
 [ 0.4  5.4 -2.6 -0.6 -2.6]
 [-1.8  1.2  1.2 -1.8  1.2]
 [-2.  -2.   1.   4.  -1. ]
 [ 1.   1.   3.  -3.  -2. ]
 [ 0.2  0.2  1.2  1.2 -2.8]
 [-0.2  2.8 -1.2 -3.2  1.8]
 [ 1.   1.  -6.   2.   2. ]]


#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)