# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)

1.26.4


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
a = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
a.nbytes
answer(4)

Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
# help(np.add)
answer(5)

%run `python -c "import numpy; numpy.info(numpy.add)"`


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [8]:
answer(6)

Z = np.zeros(10)
Z[4] = 1
print(Z)


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
a = np.random.randint(10, 50, 10)
a


array([45, 19, 11, 41, 12, 49, 44, 19, 47, 26])

In [10]:
answer(7)

Z = np.arange(10,50)
print(Z)


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [11]:
a[::-1]

array([26, 47, 19, 44, 49, 12, 41, 11, 19, 45])

In [12]:
answer(8)

Z = np.arange(50)
Z = Z[::-1]
print(Z)


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
a = np.random.randint(0, 9, 9).reshape(3, 3)
a

array([[4, 6, 4],
       [7, 0, 8],
       [7, 1, 5]])

In [14]:
answer(9)

Z = np.arange(9).reshape(3, 3)
print(Z)


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [15]:
a = np.array([1, 2, 0, 0, 4, 0])
a = np.where(a == 0)
a

(array([2, 3, 5], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [16]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [17]:
np.random.random([3, 3, 3])

array([[[0.56473572, 0.20638199, 0.34138224],
        [0.66455687, 0.92626103, 0.43588587],
        [0.84736304, 0.03899334, 0.55026105]],

       [[0.09080021, 0.25894849, 0.46660504],
        [0.14689803, 0.39266981, 0.39643846],
        [0.65321236, 0.0114352 , 0.81475957]],

       [[0.08099677, 0.98676617, 0.51665631],
        [0.45945008, 0.61524516, 0.74942096],
        [0.00567182, 0.65707237, 0.85809658]]])

In [18]:
answer(12)

Z = np.random.random((3,3,3))
print(Z)


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [19]:
a = np.random.random([10, 10])
print(a.min(), a.max())

0.006746316581113354 0.9870405292440533


In [20]:
answer(13)

Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [21]:
a = np.random.random(30).mean()
print(a)

0.4517700270086176


In [22]:
answer(14)

Z = np.random.random(30)
m = Z.mean()
print(m)


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [23]:
a = np.ones([4, 4])
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [24]:
answer(15)

Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [25]:
a = np.ones([3, 3])
a = np.pad(a, pad_width=1, mode="constant")  # padding
a

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
answer(16)

Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [27]:
0.3 == 3 * 0.1

False

In [28]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [29]:
answer(17)

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [30]:
np.diag([1, 2, 3, 4], k=0)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [31]:
a = np.zeros([8, 8])
a[::2, ::2] = 1
a[1::2, 1::2] = 1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [32]:
a = np.array(np.arange(336).reshape(6, 7, 8))
a[1, 5, 3]

99

In [33]:
print(np.unravel_index(99,(6,7,8)))  # 1次元のインデックスを多次元インデックスに変換してくれる

(1, 5, 3)


In [34]:
answer(20)

print(np.unravel_index(99,(6,7,8)))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [35]:
a = [[0, 1], [1, 0]]
b = np.tile(a, (4, 4))
b

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [36]:
answer(21)

Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [37]:
a = np.array(np.random.random((5, 5)))
a_min = a.min()
a_max = a.max()
a = (a - a_min) / (a_max - a_min)
a


array([[0.29756352, 0.22653821, 0.75893121, 0.71960006, 0.80761726],
       [1.        , 0.82031157, 0.35361747, 0.86993197, 0.33710252],
       [0.28491937, 0.89109653, 0.23876241, 0.28001913, 0.50489321],
       [0.82700538, 0.4461817 , 0.41238459, 0.80825594, 0.19949806],
       [0.31871449, 0.5302037 , 0.45494581, 0.63251003, 0.        ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [38]:
color = np.dtype([("r", np.ubyte),
                 ("g", np.ubyte),
                 ("b", np.ubyte),
                 ("a", np.ubyte)])

In [39]:
answer(23)

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [40]:
a = np.array(np.random.random([5, 3]))
b = np.array(np.random.random([3, 2]))
np.matmul(a, b)

array([[0.49533247, 0.77931815],
       [0.54832128, 0.48940503],
       [0.62393175, 0.76928377],
       [1.27002331, 0.69896146],
       [1.3444845 , 0.35328007]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [41]:
a = np.array(np.arange(11))
a[((3 < a) & (a < 8))] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

In [42]:
answer(25)

# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)


In [43]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [44]:
sum(range(5), -1)

9

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [45]:
####
"""python
1. ok
2. no
3. ok
4. ok
5. ok
6. no
"""

'python\n1. ok\n2. no\n3. ok\n4. ok\n5. ok\n6. no\n'

In [46]:
Z = np.array([1, 2, 3])
1j*Z  # jは虚数単位

array([0.+1.j, 0.+2.j, 0.+3.j])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [47]:
np.array(0) / np.array(0)  # numpyはエラーが出たときに中断せずに、nanを返す

C:\Users\CHU1P\AppData\Local\Temp\ipykernel_4972\941235769.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)  # numpyはエラーが出たときに中断せずに、nanを返す


nan

In [48]:
np.array(0) // np.array(0)

C:\Users\CHU1P\AppData\Local\Temp\ipykernel_4972\2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [49]:
np.array([np.nan]).astype(int).astype(float)  # np.nanはint型に変えるとその方の最小値になる

C:\Users\CHU1P\AppData\Local\Temp\ipykernel_4972\2424127791.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)  # np.nanはint型に変えるとその方の最小値になる


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [50]:
a = np.array(np.random.uniform(-10, 10, 5))
print(a)
a = np.where(a >= 0, np.ceil(a), np.floor(a))
print(a)

[-8.02440572  8.38888631  6.74614791 -8.67442625 -8.91790663]
[-9.  9.  7. -9. -9.]


In [51]:
answer(29)

# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))


#### 30. How to find common values between two arrays? (★☆☆)

In [52]:
a = np.random.randint(1, 9, 5)
b = np.random.randint(1, 9, 5)
print(a, b)
np.intersect1d(a, b)  # 共通の値を出力する, 出力はsortされている

[4 3 1 4 8] [2 2 3 7 3]


array([3])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [53]:
answer(31)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


In [54]:
defaults = np.seterr(all="ignore")
z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [55]:
np.emath.sqrt(-1)  # emathは複素数が答えの場合は複素数に変える

1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [56]:
print(np.datetime64("today", "D") - np.timedelta64(1, "D"))
print(np.datetime64("today", "D"))
print(np.datetime64("today", "D") + np.timedelta64(1, "D"))

2025-06-26
2025-06-27
2025-06-28


In [57]:
import pandas as pd

today = pd.Timestamp("today")
yesterday = (today - pd.Timedelta(days=1)).strftime("%Y-%m-%d")
tomorrow = (today + pd.Timedelta(days=1)).strftime("%Y-%m-%d")
today = today.strftime("%Y-%m-%d")
print(yesterday, today, tomorrow)

2025-06-26 2025-06-27 2025-06-28


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [58]:
a = pd.date_range(start="2016-07-01", end="2016-07-31", freq="D")
a

DatetimeIndex(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
               '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
               '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
               '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
               '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
               '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
               '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
               '2016-07-29', '2016-07-30', '2016-07-31'],
              dtype='datetime64[ns]', freq='D')

In [59]:
np.arange("2016-07", "2016-08", dtype="datetime64[D]")

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [60]:
answer(34)

Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [61]:
answer(35)

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


In [62]:
A = np.ones(3) * 1
B = np.ones(3) * 2
print(B)
print(np.add(A, B, out=B))  # numpyのaddやnegativeを使うことによってメモリの使用を削減できる
np.negative(A, out=A)
print(np.divide(A, 2, out=A))

[2. 2. 2.]
[3. 3. 3.]
[-0.5 -0.5 -0.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [63]:
a = np.array([9.43702508, 5.44392995, -8.80030341, -4.46399976, -1.06240269])
print(a.astype(int))
print(np.where(a >= 0, np.floor(a), np.ceil(a)))
print(a // 1)
print(np.trunc(a))  # np.where(a >= 0, np.floor(a), np.ceil(a))これと同じ

[ 9  5 -8 -4 -1]
[ 9.  5. -8. -4. -1.]
[ 9.  5. -9. -5. -2.]
[ 9.  5. -8. -4. -1.]


In [64]:
answer(36)

Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [65]:
np.array(np.tile([0, 1, 2, 3, 4], (5, 1)))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [66]:
answer(37)

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [67]:
def int_generator():
    for i in range(10):
        yield i

print(np.fromiter(int_generator(), dtype=int))

[0 1 2 3 4 5 6 7 8 9]


In [68]:
answer(38)

def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [69]:
np.nextafter(0, 1)

5e-324

In [70]:
np.random.uniform(np.nextafter(0, 1), 1, 10)

array([0.32057174, 0.11698141, 0.27580872, 0.22884321, 0.94437128,
       0.49822175, 0.13456384, 0.59207146, 0.97792058, 0.12411437])

In [71]:
np.linspace(0, 1, 11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [72]:
answer(39)

Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [73]:
a = np.random.random(10)
a.sort()
print(a)

[0.05185388 0.1764728  0.21936576 0.28889078 0.40320226 0.65693181
 0.7009673  0.72906598 0.76095242 0.85852746]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [74]:
answer(41)

# Author: Evgeni Burovski

Z = np.arange(10)
np.add.reduce(Z)


In [75]:
a = np.arange(10)
np.add.reduce(a)

45

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [76]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
equal = np.allclose(A, B)
print(equal)

False


In [77]:
answer(42)

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)


#### 43. Make an array immutable (read-only) (★★☆)

In [78]:
a = np.array([1, 2, 3])
a.flags.writeable = False
a

array([1, 2, 3])

In [79]:
answer(43)

Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [80]:
A = np.array([[0.16702026, 0.17824744],
 [0.66112783, 0.93869856],
 [0.67644807, 0.3256588 ],
 [0.24854642, 0.58445634],
 [0.0551434, 0.4596011 ],
 [0.49144912, 0.17056799],
 [0.86365082, 0.42253366],
 [0.49300285, 0.74969368],
 [0.5517937, 0.35342211],
 [0.33419615, 0.939642]])
sheta = np.arctan2(A[:, 1] ,A[:, 0])
np.square(A, out=A)
A = np.sum(A, axis=1)
R = np.sqrt(A)
print(R)
print(sheta)


[0.24427017 1.14814851 0.75075672 0.63510986 0.46289736 0.52020734
 0.96147149 0.89726943 0.65527359 0.99730344]
[0.81790403 0.95718855 0.44867724 1.16870473 1.45138613 0.33406354
 0.45500367 0.98909295 0.56966557 1.22908521]


In [81]:
Z = np.random.random((10,2))
print(Z)
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[[0.38997915 0.96843824]
 [0.54047564 0.6792646 ]
 [0.14547822 0.17442118]
 [0.1376703  0.55815858]
 [0.87436976 0.72862214]
 [0.4827376  0.44043636]
 [0.72682736 0.09861731]
 [0.09666995 0.48462214]
 [0.54870804 0.31295064]
 [0.38613011 0.30855776]]
[1.04400976 0.86805202 0.22712697 0.57488618 1.13816198 0.6534675
 0.73348714 0.49416971 0.6316792  0.49427153]
[1.18797424 0.89869655 0.87562771 1.32897226 0.69472523 0.73960867
 0.13485835 1.37390573 0.51832579 0.6741938 ]


In [82]:
answer(44)

Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [83]:
a = np.random.random(10)
a[a.argmax()] = 0
a

array([0.69445435, 0.68759136, 0.28126244, 0.        , 0.45712289,
       0.46595267, 0.46300273, 0.73825836, 0.05203157, 0.24665283])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [84]:
structed_dtype = np.dtype([("x", float), ("y", float)])
a = np.array(np.random.uniform(0, np.nextafter(1, 2), 10).reshape(-1, 2))
a.dtype = structed_dtype
a

array([[(0.72909698, 0.21830827)],
       [(0.95433488, 0.38470509)],
       [(0.77003563, 0.98608572)],
       [(0.06608249, 0.61784942)],
       [(0.96892135, 0.19270912)]], dtype=[('x', '<f8'), ('y', '<f8')])

In [85]:
answer(46)

Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [86]:
X = np.array(np.random.random(5))
Y = np.array(np.random.random(5))
C = 1 / np.subtract.outer(X, Y)
print(C)

[[ -2.68650646 -22.00607787  -1.86161436  -1.22832683  -5.10484672]
 [ -2.74491889 -26.65184896  -1.8894768   -1.24039557  -5.31996603]
 [ -1.84714541  -4.66010903  -1.41580202  -1.01702414  -2.73944435]
 [  2.69344869   1.43254188   4.84651851 -14.16155591   1.82611849]
 [  9.48398136   2.31358524 -16.80768366  -2.97226295   3.54887654]]


In [87]:
answer(47)

# Author: Evgeni Burovski

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))


In [88]:
a = np.array(np.random.randint(1, 10, 10))
b = np.array(np.random.randint(1, 10, 3))
np.add.outer(a, b)

array([[ 9,  4, 10],
       [15, 10, 16],
       [10,  5, 11],
       [ 7,  2,  8],
       [12,  7, 13],
       [ 7,  2,  8],
       [12,  7, 13],
       [11,  6, 12],
       [ 7,  2,  8],
       [12,  7, 13]])

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [89]:
print(np.iinfo(np.int8))
print(np.finfo(np.float16))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for float16
---------------------------------------------------------------
precision =   3   resolution = 1.00040e-03
machep =    -10   eps =        9.76562e-04
negep =     -11   epsneg =     4.88281e-04
minexp =    -14   tiny =       6.10352e-05
maxexp =     16   max =        6.55040e+04
nexp =        5   min =        -max
smallest_normal = 6.10352e-05   smallest_subnormal = 5.96046e-08
---------------------------------------------------------------



In [90]:
hint(48)

hint: np.iinfo, np.finfo, eps


#### 49. How to print all the values of an array? (★★☆)

In [91]:
np.set_printoptions(threshold=float("inf"))
# np.set_printoptions(threshold=1000)
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [92]:
hint(49)

hint: np.set_printoptions


In [93]:
answer(49)

np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [94]:
a = np.arange(100)
v = np.random.uniform(0, 100)
index = np.abs(np.subtract(a, v)).argmin()
a[index]

51

In [95]:
answer(50)

Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [96]:
a = np.zeros(2, dtype=[("position", [("x", float, 1),
                                      ("y", float, 1)]),
                        ("color", [("r", float, 1),
                                   ("g", float, 1),
                                   ("b", float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\CHU1P\AppData\Local\Temp\ipykernel_4972\4134159954.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = np.zeros(2, dtype=[("position", [("x", float, 1),


In [97]:
answer(51)

Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [98]:
a = np.random.random((10,2))
delta_coords = a[:, np.newaxis, :] - a[np.newaxis, :, :]
r = np.sqrt(np.sum(np.square(delta_coords), axis=2))
print(r[:5])

[[0.         0.57818635 0.41790783 0.51539549 0.58636442 0.50384777
  0.34747682 0.32243711 0.57253924 0.3840556 ]
 [0.57818635 0.         0.53036718 0.17550258 0.79242109 0.44899124
  0.89694646 0.37838373 0.10173768 0.9005671 ]
 [0.41790783 0.53036718 0.         0.59939608 0.26507048 0.13767575
  0.53661455 0.56872068 0.45419605 0.49417152]
 [0.51539549 0.17550258 0.59939608 0.         0.86350475 0.55296819
  0.85809115 0.24105341 0.26353635 0.87877184]
 [0.58636442 0.79242109 0.26507048 0.86350475 0.         0.35747737
  0.53874654 0.81002377 0.71059193 0.46322499]]


In [99]:
a[:, np.newaxis, :] - a[np.newaxis, :, :]

array([[[ 0.        ,  0.        ],
        [ 0.28706469, -0.50188975],
        [ 0.41773178,  0.01212918],
        [ 0.11156682, -0.50317527],
        [ 0.52914213,  0.25264965],
        [ 0.49320395, -0.10301666],
        [-0.00119364,  0.34747477],
        [-0.04438642, -0.3193674 ],
        [ 0.36723276, -0.43925081],
        [ 0.08239804,  0.37511234]],

       [[-0.28706469,  0.50188975],
        [ 0.        ,  0.        ],
        [ 0.13066709,  0.51401893],
        [-0.17549787, -0.00128553],
        [ 0.24207743,  0.75453939],
        [ 0.20613926,  0.39887309],
        [-0.28825834,  0.84936452],
        [-0.33145112,  0.18252234],
        [ 0.08016807,  0.06263893],
        [-0.20466666,  0.87700209]],

       [[-0.41773178, -0.01212918],
        [-0.13066709, -0.51401893],
        [ 0.        ,  0.        ],
        [-0.30616496, -0.51530445],
        [ 0.11141035,  0.24052047],
        [ 0.07547217, -0.11514584],
        [-0.41892542,  0.3353456 ],
        [-0.4621182 , -0

In [100]:
Z = np.random.random((10,2))
X,Y = Z[:, np.newaxis, 0], Z[:, np.newaxis, 1]
D = np.sqrt((X - X.T)**2 + (Y - Y.T)**2)
print(D)

[[0.         0.65136253 0.96260735 0.55390571 0.74505182 0.61494121
  0.22770783 1.02199295 0.98723182 0.65348454]
 [0.65136253 0.         0.6633655  0.46000639 0.86636361 0.7879698
  0.4701922  0.48064124 0.49858094 0.64878984]
 [0.96260735 0.6633655  0.         0.40875803 0.52725833 0.56332833
  0.74217328 0.37981471 0.28680307 0.38155223]
 [0.55390571 0.46000639 0.40875803 0.         0.40635722 0.33661081
  0.33632434 0.55139964 0.48759448 0.19196957]
 [0.74505182 0.86636361 0.52725833 0.40635722 0.         0.13026522
  0.60810553 0.84888368 0.76172865 0.22276246]
 [0.61494121 0.7879698  0.56332833 0.33661081 0.13026522 0.
  0.48594741 0.84071638 0.76014616 0.1942306 ]
 [0.22770783 0.4701922  0.74217328 0.33632434 0.60810553 0.48594741
  0.         0.79795687 0.76029746 0.46733833]
 [1.02199295 0.48064124 0.37981471 0.55139964 0.84888368 0.84071638
  0.79795687 0.         0.09340481 0.6474168 ]
 [0.98723182 0.49858094 0.28680307 0.48759448 0.76172865 0.76014616
  0.76029746 0.093404

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [101]:
A = np.random.randn(10)
print(A)
# A[:]とすることでAの要素だけを書き換えれる
A[:] = A.astype(np.int32)
print(A)

[ 0.01010739 -0.25271242  1.01941378  1.00416744  1.44108844  1.94746579
  1.49881396  0.3864562  -1.10485369  0.61659867]
[ 0.  0.  1.  1.  1.  1.  1.  0. -1.  0.]


In [102]:
answer(53)

# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [103]:
hint(54)

hint: np.genfromtxt


In [104]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5
             6, , , 7, 8
              , , 9,10,11""")
data = np.genfromtxt(s, delimiter=",", dtype=float)
data


array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

In [105]:
from io import StringIO
import pandas as pd

s = StringIO("""1, 2, 3, 4, 5
6, , , 7, 8
 , , 9,10,11""")
data = pd.read_csv(s, sep=",", header=None, na_values=[" "])
print(data)

     0    1    2   3   4
0  1.0  2.0  3.0   4   5
1  6.0  NaN  NaN   7   8
2  NaN  NaN  9.0  10  11


In [106]:
answer(54)

from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [107]:
A = np.array([[1, 2], [3, 4]])
for idx, val in np.ndenumerate(A):
    print(idx, val)


(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [108]:
hint(56)

hint: np.meshgrid, np.exp


In [109]:
answer(56)

X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)


In [110]:
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
D = np.sqrt(X*X + Y*Y)
sigma, mu = 1.0, 0.0
y = (np.exp(-(D - mu) / (2 * sigma)) ** 2)
print(y)

[[0.24311673 0.28171437 0.31855539 0.34850854 0.3656225  0.3656225
  0.34850854 0.31855539 0.28171437 0.24311673]
 [0.28171437 0.33288976 0.38449907 0.42904348 0.45581229 0.45581229
  0.42904348 0.38449907 0.33288976 0.28171437]
 [0.31855539 0.38449907 0.45581229 0.52315183 0.56747549 0.56747549
  0.52315183 0.45581229 0.38449907 0.31855539]
 [0.34850854 0.42904348 0.52315183 0.62412506 0.70372742 0.70372742
  0.62412506 0.52315183 0.42904348 0.34850854]
 [0.3656225  0.45581229 0.56747549 0.70372742 0.85458882 0.85458882
  0.70372742 0.56747549 0.45581229 0.3656225 ]
 [0.3656225  0.45581229 0.56747549 0.70372742 0.85458882 0.85458882
  0.70372742 0.56747549 0.45581229 0.3656225 ]
 [0.34850854 0.42904348 0.52315183 0.62412506 0.70372742 0.70372742
  0.62412506 0.52315183 0.42904348 0.34850854]
 [0.31855539 0.38449907 0.45581229 0.52315183 0.56747549 0.56747549
  0.52315183 0.45581229 0.38449907 0.31855539]
 [0.28171437 0.33288976 0.38449907 0.42904348 0.45581229 0.45581229
  0.42904348 

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [111]:
A = np.zeros((5, 5))
p = 3
idx = np.unravel_index(np.random.randint(0, 25, p, ), (5, 5))
A[idx] = 1
print(A)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]


In [112]:
A = np.zeros((5, 5))
# choiceが重複のない選択をできる
np.put(A, np.random.choice(25, p, replace=False), 1)
print(A)

[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [113]:
answer(57)

# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [114]:
A = np.random.randint(0, 10, (10, 5)).astype(np.float64)
# keepdimsをしないとテンソルとして残らないため
A[:] -= np.mean(A, axis=1, keepdims=True)
print(A)

[[-1.8  4.2  3.2 -1.8 -3.8]
 [ 2.  -2.   4.  -3.  -1. ]
 [-2.   3.  -1.  -2.   2. ]
 [ 1.2 -3.8  2.2  3.2 -2.8]
 [ 3.  -1.  -2.   2.  -2. ]
 [ 2.   4.   0.  -5.  -1. ]
 [-0.6  0.4 -1.6 -1.6  3.4]
 [-2.2 -0.2  1.8 -1.2  1.8]
 [-1.2 -4.2  2.8  3.8 -1.2]
 [-1.6 -1.6 -2.6  2.4  3.4]]


#### 59. How to sort an array by the nth column? (★★☆)

In [115]:
A = np.random.randint(0, 10, (5, 5))
print(A)
A.argsort()
A[A[:, 1].argsort()]

[[6 2 1 4 3]
 [9 7 2 6 5]
 [4 5 1 9 1]
 [7 1 2 0 8]
 [9 9 9 7 1]]


array([[7, 1, 2, 0, 8],
       [6, 2, 1, 4, 3],
       [4, 5, 1, 9, 1],
       [9, 7, 2, 6, 5],
       [9, 9, 9, 7, 1]])

In [116]:
A = np.random.randint(0, 10, (5, 5))
print(A)
A = pd.DataFrame(A)
A.sort_values(by=1, axis=1)

[[3 3 8 0 9]
 [5 5 8 8 7]
 [7 7 6 8 6]
 [5 6 8 0 0]
 [2 1 2 0 3]]


0  1  4  2  3
0  3  3  9  8  0
1  5  5  7  8  8
2  7  7  6  6  8
3  5  6  0  8  0
4  2  1  3  2  0

In [117]:
answer(59)

# Author: Steve Tjoa

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [118]:
hint(60)

hint: any, ~


In [119]:
answer(60)

# Author: Warren Weckesser

# null : 0 
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))


In [120]:
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))
print(Z)

[False False  True]
[[ 0.  1. nan]
 [ 1.  2. nan]
 [ 4.  5. nan]]


In [121]:
Z = pd.DataFrame(Z)
# axis=Noneとすればdf全体で見てくれる
Z.isna().any(axis=0)


0    False
1    False
2     True
dtype: bool

#### 61. Find the nearest value from a given value in an array (★★☆)

In [122]:
A = np.random.rand(3, 3)
v = 7
idx = np.abs(A - v).argmin()
A[idx]

IndexError: index 4 is out of bounds for axis 0 with size 3

In [ ]:
A = pd.DataFrame(np.random.rand(3, 3))
v = 7
A.iloc[(A - v).abs().idxmin()]

0         1         2
1  0.911823  0.074380  0.382479
2  0.804492  0.504122  0.437735
0  0.311121  0.438654  0.674509

In [ ]:
answer(61)

Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
A = np.arange(3).reshape(1, 3)
B = np.arange(3).reshape(3, 1)

it = np.nditer([A, B, None])
for x, y, z in it:
    z[...] = x + y
result = it.operands[2].reshape(3, 3)
print(result)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return
        # objにnameがあればそのままなければno nameを
        self.name = getattr(obj, "name", "no name")

A = NamedArray(np.arange(10), "range_10")
print(A.name)

range_10


In [ ]:
hint(63)

hint: class method


In [ ]:
answer(63)

class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
a = np.array([1, 2, 3, 4, 5])
i = np.array([0, 1, 1, 3])
np.add.at(a, i, 1)
print(a)

[2 4 3 5 5]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
a = np.array([1, 2, 3, 4, 5])
i = np.array([0, 1, 1, 3])
F = np.zeros(5)
np.add.at(F, i, a[i])
F

array([1., 4., 0., 4., 0.])

In [ ]:
X = [1, 2, 3, 4, 5]
I = [0, 1, 1, 3, 5]
F = np.bincount(I,X)
print(F)

[1. 5. 0. 4. 0. 5.]


In [ ]:
answer(65)

# Author: Alan G Isaac

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
answer(66)

# Author: Fisher Wang

w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

# Faster version
# Author: Mark Setchell
# https://stackoverflow.com/a/59671950/2836621

w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)


In [ ]:
np.random.randint(0, 4, (2, 3))

array([[3, 3, 2],
       [0, 2, 3]])

In [ ]:
img = np.random.randint(0, 4, (256, 256, 3)).astype(np.ubyte)
# 65536 x 3の2次元テンソルになる
colors = np.unique(img.reshape(-1, 3), axis=0)
print(colors.shape)

(64, 3)


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
A = np.array(np.random.randint(0, 10, (3, 3, 3, 3)))
A = A.sum(axis=(-2, -1))
A.shape

(3, 3)

In [ ]:
answer(67)

A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)

D_means = []
for i in range(10):
    S_idx = S == i
    D_means.append(D[S_idx].mean())
print(D_means)
    

D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

D_S = pd.DataFrame({"D": D, "S": S})
D_S.groupby("S").mean()

[0.4240470401983462, 0.5394543263135347, 0.46291729546008653, 0.6420579774663644, 0.5949007750119155, 0.46999436393803556, 0.5539751501597625, 0.5483009794792417, 0.3863306995677012, 0.46743323255891467]
[0.42404704 0.53945433 0.4629173  0.64205798 0.59490078 0.46999436
 0.55397515 0.54830098 0.3863307  0.46743323]


D
S          
0  0.424047
1  0.539454
2  0.462917
3  0.642058
4  0.594901
5  0.469994
6  0.553975
7  0.548301
8  0.386331
9  0.467433

In [ ]:
answer(68)

# Author: Jaime Fernández del Río

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A = np.random.randint(0, 10, (3, 3))
B = np.random.randint(0, 10, (3, 3,))

C = np.matmul(A, B)
print(C)
print(C.diagonal())

np.sum(A * B.T, axis=1)



[[37 51 56]
 [58 38 66]
 [48 44 61]]
[37 38 61]


array([37, 38, 61])

In [ ]:
answer(69)

# Author: Mathieu Blondel

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
A = np.array([1, 2, 3, 4, 5])
C = []
for a in A:
    C.append(a)
    C.extend([0, 0, 0])
print(C)

[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0]


In [ ]:
C = np.zeros(len(A) * 4, dtype=int)
C[::4] = A
print(C)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5 0 0 0]


In [ ]:
answer(70)

# Author: Warren Weckesser

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)


#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

In [ ]:
A = np.random.randint(0, 10, [5, 5, 3])
B = np.random.randint(0, 10, [5, 5])
C = A * B[:, :, np.newaxis]
print(C.shape)

(5, 5, 3)


In [ ]:
answer(71)

A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])


#### 72. How to swap two rows of an array? (★★★)

In [ ]:
A = np.arange(8).reshape(2, 4)
A[[0, 1]] = A[[1, 0]]
A


array([[4, 5, 6, 7],
       [0, 1, 2, 3]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
A = np.random.randint(0, 100, (10, 3))
F = np.roll(A.repeat(2, axis=1), -1, axis=1)
F = F.reshape(-1, 2)
F = np.sort(F, axis=1)
G = F.view(dtype=[("p0", F.dtype), ("p1", F.dtype)])
G = np.unique(G)
F = np.unique(F, axis=0)
# F = np.unique(F, axis=1)
print(F.shape)
print(G.shape)


(30, 2)
(30,)


In [ ]:
answer(73)

# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
hint(74)

hint: np.repeat


In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
A

array([1, 1, 2, 3, 4, 4, 6])

In [ ]:
answer(74)

# Author: Jaime Fernández del Río

C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
A = np.arange(7)
windows = np.lib.stride_tricks.sliding_window_view(A, window_shape=3)
windows_avg = windows.mean(axis=1)
print(windows)
print(windows_avg)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
[1. 2. 3. 4. 5.]


In [ ]:
answer(75)

# Author: Jaime Fernández del Río

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

# Author: Jeff Luo (@Jeff1999)
# make sure your NumPy >= 1.20.0

from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
A = np.arange(30)
A = np.lib.stride_tricks.sliding_window_view(A, 3)
print(A)

[[ 0  1  2]
 [ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13 14]
 [13 14 15]
 [14 15 16]
 [15 16 17]
 [16 17 18]
 [17 18 19]
 [18 19 20]
 [19 20 21]
 [20 21 22]
 [21 22 23]
 [22 23 24]
 [23 24 25]
 [24 25 26]
 [25 26 27]
 [26 27 28]
 [27 28 29]]


In [ ]:
answer(76)

# Author: Joe Kington / Erik Rigtorp
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

# Author: Jeff Luo (@Jeff1999)

Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
A = np.random.randint(0, 2, 5).astype(bool)
np.logical_not(A, out=A)
print(A)

A = np.random.uniform(-1.0, 1.0, 5)
np.negative(A, out=A)
print(A)

[False False False False  True]
[-0.68254539  0.15621625  0.33562601  0.40819257  0.29191556]


In [ ]:
answer(77)

# Author: Nathaniel J. Smith

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
import numpy as np

In [ ]:
P0 = np.random.uniform(-10, 10, (10, 2))

P1 = np.random.uniform(-10, 10, (10, 2))

p = np.random.uniform(-10, 10, (1, 2))


# dx = B["x"] - A["x"]
# dy = B["y"] - A["y"]
# dydx = P1 - P0
# m = dydx[:, 0] / dydx[:, 1]
# L = np.abs(m * p[0, 0] - p[0, 1] - m * P0[:, 0] + P0[:, 1]) / np.sqrt(m ** 2 + 1)
# print(L)


a = P1 - P0
b = p - P0
# vector a の2乗
A = (a**2).sum(axis=1)
U = np.sum(a * b, axis=1) / A
H = U[:, np.newaxis] * a

dist_on = np.linalg.norm(p - (P0 + H), axis=1)
# 始点側
dist_start = np.linalg.norm(p - P0, axis=1)
# 終点側
dist_end = np.linalg.norm(p - P1, axis=1)

# 距離を場合分けで選択
distance = np.where(U < 0, dist_start,
            np.where(U > 1, dist_end, dist_on))
print(distance)


def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))


print(distance(P0, P1, p))

[ 4.972141   12.59314574  7.70614502 10.25443551 12.0304646   1.07514984
  7.13835788  2.90364086 10.51516188 19.05340589]
[ 4.93902359 11.07506371  3.36686018 10.25443551 12.0304646   0.71593878
  6.5131383   2.90364086 10.51516188 19.05340589]


In [ ]:
answer(78)

def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10, 2))

P1 = np.random.uniform(-10, 10, (10, 2))

p = np.random.uniform(-10, 10, (5 , 2))


# dx = B["x"] - A["x"]
# dy = B["y"] - A["y"]
# dydx = P1 - P0
# m = dydx[:, 0] / dydx[:, 1]
# L = np.abs(m * p[0, 0] - p[0, 1] - m * P0[:, 0] + P0[:, 1]) / np.sqrt(m ** 2 + 1)
# print(L)


a = P1 - P0
# (10, 2) -> (1, 10, 2)
a = a[np.newaxis, :, :]
# (5, 1, 2) - (1, 10, 2) = (5, 10, 2)
b = p[:, np.newaxis, :] - P0[np.newaxis, :, :]

# vector a の2乗
# (1, 10, 2) -> (1, 10)
A = (a**2).sum(axis=2)
# (5, 10, 2) -> (5, 10)
U = np.sum(a * b, axis=2) / A
# (5, 10, 1) * (1, 10, 2) = (5, 10, 2)
H = U[:, :, np.newaxis] * a

# (5, 1, 2) - (1, 10, 2) - (5, 10, 2) = (5, 10, 2) -> (5, 10)
dist_on = np.linalg.norm(p[:, np.newaxis, :] - (P0[np.newaxis, :, :] + H), axis=2)
# 始点側
# (5, 1, 2) - (1, 10, 2) = (5, 10, 2) -> (5, 10)
dist_start = np.linalg.norm(p[:, np.newaxis,: ] - P0[np.newaxis, :, :], axis=2)
# 終点側
# (5, 1, 2) - (1, 10, 2) = (5, 10, 2) -> (5, 10)
dist_end = np.linalg.norm(p[:, np.newaxis] - P1[np.newaxis, :, :], axis=2)

# 距離を場合分けで選択
distance = np.where(U < 0, dist_start,
            np.where(U > 1, dist_end, dist_on))
print(distance)


[[15.3836176   9.96101995  2.52460973 11.81180037  7.28371263 11.68234773
   7.93049069  0.33853095  4.77357939  8.47502544]
 [ 0.7540057   4.61967411 11.43476048  0.18662627  8.80338834  4.43139115
   7.05192126  8.58760275 11.88866256  5.86960014]
 [ 5.14683082 11.75229397  8.59011045  3.04246146  5.2885472   1.95305626
   4.97529599  2.53434341 11.44854093  4.28779504]
 [ 1.04906969  5.70844965 13.31820339  1.07779248 10.93014948  6.11528108
   8.79591118 10.12360631 13.47732807  7.1771081 ]
 [ 1.61849145 11.46421977 11.31591351  2.0886885   6.09452321  1.87319084
   6.59152563  0.70935025 13.6492935   5.82117714]]


#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
answer(80)

# Author: Nicolas Rougier

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)


In [ ]:

def pad(array, N, i, j, fill=-1):
    out = np.zeros([N, N])
    (row, column) = array.shape
    for a in range(N):
        for b in range(N):
            aa = i - N // 2 + a
            bb = j - N // 2 + b
            if 0 <= aa < row and 0 <= bb < column:
                out[a, b] = array[aa, bb]
            else:
                out[a, b] = fill
    print(out)
            
a = np.arange(16).reshape(4,4)           
pad(a, 3, 0, 0)

[[-1. -1. -1.]
 [-1.  0.  1.]
 [-1.  4.  5.]]


In [ ]:
def get_extract(arr, center, shape, fill=-1):
    out = np.full(shape, fill_value=fill, dtype=arr.dtype)
    arr_shape = np.array(arr.shape)
    shape = np.array(shape)
    center = np.array(center)

    start = center - shape // 2
    end = start + shape 

    arr_start = np.maximum(start, 0)
    arr_end = np.minimum(end, arr_shape)

    out_start = arr_start - start
    out_end = out_start + (arr_end - arr_start)

    out_slices = tuple(slice(s, e) for s, e in zip(out_start, out_end))
    arr_slices = tuple(slice(s, e) for s, e in zip(arr_start, arr_end))
    out[out_slices] = arr[arr_slices]
    print(out)


A = np.arange(16).reshape(4, 4)

get_extract(A, center=(0, 0), shape=(3, 3))

[[-1 -1 -1]
 [-1  0  1]
 [-1  4  5]]


In [ ]:
import numpy as np

def extract_centered_subarray(arr, center, shape, fill=0):
    out = np.full(shape, fill, dtype=arr.dtype)
    arr_shape = np.array(arr.shape)
    shape = np.array(shape)
    center = np.array(center)

    # 元配列と出力配列のスライス範囲を計算
    start = center - shape // 2
    end = center + (shape + 1) // 2

    # 元配列側の有効範囲
    arr_start = np.maximum(start, 0)
    arr_end = np.minimum(end, arr_shape)

    # 出力配列側の有効範囲
    out_start = arr_start - start
    out_end = out_start + (arr_end - arr_start)

    # スライスしてコピー
    out_slices = tuple(slice(s, e) for s, e in zip(out_start, out_end))
    arr_slices = tuple(slice(s, e) for s, e in zip(arr_start, arr_end))
    out[out_start[0]:out_end[0], out_start[1]:out_end[1]] = \
        arr[arr_start[0]:arr_end[0], arr_start[1]:arr_end[1]]
    print(out_slices)
    return out

# 例
a = np.arange(16).reshape(4,4)
print(extract_centered_subarray(a, center=(1, 1), shape=(3, 3), fill=-1))


(slice(0, 3, None), slice(0, 3, None))
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
Z = np.arange(1, 15)
Z = np.lib.stride_tricks.sliding_window_view(Z, 4)
Z

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

In [ ]:
answer(81)

# Author: Stefan van der Walt

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

# Author: Jeff Luo (@Jeff1999)

Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))


#### 82. Compute a matrix rank (★★★)

In [ ]:
A = np.array([[1, 2], [2, 4]])
print(np.linalg.matrix_rank(A))

1


In [ ]:
answer(82)

# Author: Stefan van der Walt

Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

# alternative solution:
# Author: Jeff Luo (@Jeff1999)

rank = np.linalg.matrix_rank(Z)
print(rank)


#### 83. How to find the most frequent value in an array?

In [ ]:
import pandas as pd
A = np.random.randint(0, 10, 20)
A = pd.DataFrame(A)
A.value_counts().reset_index()

0  count
0  0      5
1  8      3
2  1      2
3  4      2
4  7      2
5  9      2
6  2      1
7  3      1
8  5      1
9  6      1

In [ ]:
Z = np.random.randint(0, 10, 20)
# 出現しない値は0としてカウントされる
print(np.bincount(Z))

[1 3 4 0 2 0 2 1 5 2]


In [ ]:
answer(83)

Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
A = np.arange(0, 100).reshape(10, 10)
A = np.lib.stride_tricks.sliding_window_view(A, (3, 3))
A

array([[[[ 0,  1,  2],
         [10, 11, 12],
         [20, 21, 22]],

        [[ 1,  2,  3],
         [11, 12, 13],
         [21, 22, 23]],

        [[ 2,  3,  4],
         [12, 13, 14],
         [22, 23, 24]],

        [[ 3,  4,  5],
         [13, 14, 15],
         [23, 24, 25]],

        [[ 4,  5,  6],
         [14, 15, 16],
         [24, 25, 26]],

        [[ 5,  6,  7],
         [15, 16, 17],
         [25, 26, 27]],

        [[ 6,  7,  8],
         [16, 17, 18],
         [26, 27, 28]],

        [[ 7,  8,  9],
         [17, 18, 19],
         [27, 28, 29]]],


       [[[10, 11, 12],
         [20, 21, 22],
         [30, 31, 32]],

        [[11, 12, 13],
         [21, 22, 23],
         [31, 32, 33]],

        [[12, 13, 14],
         [22, 23, 24],
         [32, 33, 34]],

        [[13, 14, 15],
         [23, 24, 25],
         [33, 34, 35]],

        [[14, 15, 16],
         [24, 25, 26],
         [34, 35, 36]],

        [[15, 16, 17],
         [25, 26, 27],
         [35, 36, 37]],

    

In [ ]:
answer(84)

# Author: Chris Barker

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

# Author: Jeff Luo (@Jeff1999)

Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:
hint(85)

hint: class method


In [ ]:
answer(85)

# Author: Eric O. Lebigot
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)


In [ ]:
class Symetric(np.ndarray):
    # サブクラス(子クラス)で__setitem__をoverrideすると代入時の動作を変えれる
    def __setitem__(self, index, value):
        a = index
        i, j = a[0], a[1]
        super(Symetric, self).__setitem__((i, j), value)
        super(Symetric, self).__setitem__((j, i), value)


def symetric(Z):
    A = np.triu(Z)
    # 上三角を下三角にも反映
    # np.diagは1次元を2次元に、2次元を1次元に
    # A = A + A.T - np.diag(np.diagonal(A))
    A = A + A.T - np.eye(A.shape[0], A.shape[1]) * A
    A = A.astype(np.uint8)
    return A.view(Symetric)



A = np.arange(0, 25).reshape(5, 5)
print(symetric(A))

A = np.triu(A)
# print(A, "\n\n", A.T)


# S = symetric(A)
# S[2, 3] = 13
# print(S)


[[ 0  1  2  3  4]
 [ 1  6  7  8  9]
 [ 2  7 12 13 14]
 [ 3  8 13 18 19]
 [ 4  9 14 19 24]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
n = 5
p = 3
A = np.random.rand(p, n, n)
v = np.random.rand(p, n, 1)

C = np.matmul(A, v)
C = np.sum(C, axis=0)
print(C)

# Aの
S = np.tensordot(A, v, axes=[[0, 2], [0, 1]])
print(S)


[[4.11312594]
 [2.63860836]
 [2.70760911]
 [3.96597825]
 [3.01693167]]
[[4.11312594]
 [2.63860836]
 [2.70760911]
 [3.96597825]
 [3.01693167]]


In [ ]:
answer(86)

# Author: Stefan van der Walt

p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
A = np.arange(0, 16*16).reshape(16, 16)
B = np.lib.stride_tricks.sliding_window_view(A, (4, 4))
B = B[::4, ::4]
# print(B)
B = np.sum(B, axis=(2, 3))
print("sum: \n\n", B)

sum: 

 [[ 408  472  536  600]
 [1432 1496 1560 1624]
 [2456 2520 2584 2648]
 [3480 3544 3608 3672]]


In [ ]:
Z = np.arange(0, 16*16).reshape(16, 16)
k = 4

windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))
print(S)


[[ 408  472  536  600]
 [1432 1496 1560 1624]
 [2456 2520 2584 2648]
 [3480 3544 3608 3672]]


In [ ]:
answer(87)

# Author: Robert Kern

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

# alternative solution:
# Author: Sebastian Wallkötter (@FirefoxMetzger)

Z = np.ones((16,16))
k = 4

windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))

# Author: Jeff Luo (@Jeff1999)

Z = np.ones((16, 16))
k = 4
print(sliding_window_view(Z, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
A = np.random.randint(0, 2, [8, 8])
print(A)

[[0 0 1 1 1 0 1 1]
 [0 0 0 0 0 1 0 1]
 [1 0 0 0 1 1 1 0]
 [1 0 1 0 1 1 1 1]
 [1 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 1 0]
 [1 0 1 0 1 0 0 0]
 [1 0 1 1 0 1 0 1]]


In [ ]:
def step_better(array):
    
    window_step = np.lib.stride_tricks.sliding_window_view(np.pad(array, pad_width=1), (3, 3))
    kernal = np.array([[1, 1, 1],
                       [1, 0, 1],
                       [1, 1, 1]])
    alive = np.sum(window_step * kernal, axis=(2, 3))
    new_array = ((array == 1) & ((alive == 2) | (alive == 3))) | ((array == 0) & (alive == 3))
    return new_array.astype(np.uint8)
                
    


# 100万回
# 1 million
new_array = step_better(A)
for i in range(999,999):
    new_array = step_better(new_array)
    # if not new_array.any():
    #     print(i)
    #     break


print("\n\n\nnew array: \n", new_array)






new array: 
 [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0]
 [0 0 0 1 1 0 0 0]]


In [ ]:
def dead_or_alive(array, a, b):
    alive = 0
    for i in range(-1, 2):
        for j in range(-1, 2):

            if (a + i < 0 or b + j < 0 or
                a + i >= array.shape[0] or 
                b + j >= array.shape[1]
            ):
                continue
            elif i == 0 and j == 0:
                continue

            elif array[a + i, b + j] == 1:
                alive += 1
    return alive



def step(array):
    new_array = array.copy()
    for i in range(array.shape[0]):
        for j in range(array.shape[1]):
            alive = dead_or_alive(array, i, j)

            if array[i, j] == 1:

                if alive == 2 or alive == 3:
                    new_array[i, j] = 1
                else:
                    new_array[i, j] = 0

            else:

                if alive == 3:
                    new_array[i, j] = 1
                else:
                    new_array[i, j] = 0
    return new_array
                
    
new_array = step(A)
for _ in range(999,999):
    new_array = step(new_array)

print("\n\n\nnew array: \n", new_array)






new array: 
 [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0]
 [0 0 0 1 1 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [ ]:
A = np.random.uniform(0, 100, 100)
A.sort()
A = A[::-1]
A[4]

92.65048162747041

In [ ]:
answer(89)

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])


In [ ]:
A = np.random.uniform(0, 100, 100)
A = A[np.argpartition(A, -3)][-3:]
A[::-1]


array([99.57661073, 98.58196914, 98.31191509])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

In [ ]:
hint(90)

hint: np.indices


In [ ]:
A = ([1, 2, 3], [4, 5], [6, 7])
arrays = [np.asarray(a) for a in A]
print(arrays)
shape = (len(x) for x in arrays)
ix = np.indices(shape, dtype=int)

ix = ix.reshape(len(arrays), -1).T
# print(ix)
# print(ix[:, 0], "\n\n")
for n in range(len(arrays)):
    ix[:, n] = arrays[n][ix[:, n]]
print(ix)


[array([1, 2, 3]), array([4, 5]), array([6, 7])]
[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    # 転置することでしっかりと要素をとってきている
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

<generator object cartesian.<locals>.<genexpr> at 0x000001E239CA97D0>
[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [ ]:
answer(90)

# Author: Stefan Van der Walt

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))


In [ ]:
A = np.arange(0, 16).reshape(2, 2, 2, 2)
print(A)
print()
print(A.reshape(4, -1).T)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]

[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
# record arrayとはnumpyで「各要素が複数の名前付きフィールド」を持つ特別な配列
# フィールド名でアクセスすることのできる配列
A = np.array([[1, 2.0, 3],
              [4, 5.0, 6]])
record = A.view([("x", "i8"), ("y", "f8"), ("z", "i8")])
print(record)


[[(4607182418800017408, 2., 4613937818241073152)]
 [(4616189618054758400, 5., 4618441417868443648)]]


In [ ]:
A = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])

# fromarraysは各列の値を指定した型にちゃんと変換してくれる
record = np.core.records.fromarrays(A.T,
                                   names="col1, col2, col3",
                                   formats = "S8, f8, i8")
print(record)


[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [ ]:
answer(91)

Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)


In [ ]:
A = [("Hello", 2.5, 3),
     ("World", 3.6, 2)]
# 文字列だけは"U10"を使う必要がある(高速な処理のために)
record = np.asarray(A, dtype=[("col1", "U10"), ("col2", np.float16), ("col3", np.int8)])
print(record.dtype)

[('col1', '<U10'), ('col2', '<f2'), ('col3', 'i1')]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
Z = np.random.randint(2, 4, 100)
A = Z ** 3
B = np.power(Z, 3)
C = np.einsum("i,i,i->i", Z, Z, Z)
print(A.sum())
print(B.sum())
print(C.sum())

1731
1731
1731


In [ ]:
A = np.arange(9).reshape(3, 3)

print(A)
s = np.einsum("ij->i", A)
v = np.einsum("ik, kj -> ij", A, A)
t = np.einsum("ik, kj, jo -> io", A, A, A)
print("\n\ns: \n", s)
print("\n\nv: \n", v)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


s: 
 [ 3 12 21]


v: 
 [[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


In [ ]:
answer(92)

# Author: Ryan G.

x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)


In [ ]:
hint(92)

hint: np.power, *, np.einsum


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:

print(A, "\n\n\n", B)

[[3 5 0]
 [4 7 3]
 [1 5 1]
 [7 5 5]
 [2 3 3]
 [2 3 3]
 [8 2 7]
 [4 7 4]] 


 [[0 1]
 [5 6]]


In [299]:
A = np.random.randint(0, 10, 24).reshape(8, 3)
B = np.random.randint(0, 10, 4).reshape(2, 2)

count = np.zeros(len(A))
for b in B:
    mask = np.array([np.isin(b, a).any() for a in A])
    idx = np.where(mask)[0]
    # print(idx)
    for id in idx:
        count[id] += 1 
print(np.where(count == 2)[0])



    

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print("\n\n", rows)


[1]


 [1]


In [266]:
mask = np.isin(A[:, :, np.newaxis], B.ravel())
mask_any = mask.any(1)
print(mask_any)

[[False]
 [ True]
 [ True]]


In [129]:
answer(93)

# Author: Gabe Schwartz

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [325]:
A = np.random.randint(0, 3, (10, 3))
print(A)
print("-" * 50)
for a in A:
    if len(np.unique(a)) != 1:
        print(a)
    else:
        continue

print("\n", "-" * 50)
U = A[np.max(A, axis=1) != np.min(A, axis=1)]
print(U)

[[2 1 2]
 [0 0 2]
 [1 2 0]
 [0 0 0]
 [2 1 2]
 [2 1 0]
 [0 1 2]
 [1 2 2]
 [1 0 1]
 [1 0 1]]
--------------------------------------------------
[2 1 2]
[0 0 2]
[1 2 0]
[2 1 2]
[2 1 0]
[0 1 2]
[1 2 2]
[1 0 1]
[1 0 1]

 --------------------------------------------------
[[2 1 2]
 [0 0 2]
 [1 2 0]
 [2 1 2]
 [2 1 0]
 [0 1 2]
 [1 2 2]
 [1 0 1]
 [1 0 1]]


In [305]:
answer(94)

# Author: Robert Kern

Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [349]:
A = np.arange(0, 5)
B = np.zeros([3, 3])
C = np.array([np.base_repr(x, base=2) for x in A])
maxlen = max(len(s) for s in C)
# zfillは文字列のメソッドで左に0を足していく
arr_pad = np.array([s.zfill(maxlen) for s in C])
print(arr_pad.dtype)
bit_matrix = np.array([list(s) for s in arr_pad], dtype=np.int8)
print(bit_matrix)

<U3
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]]


In [362]:
A = np.arange(0, 10)
I = A.astype(np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 1]
 [0 0 0 0 0 1 1 0]
 [0 0 0 0 0 1 1 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 1]]


In [350]:
answer(95)

# Author: Warren Weckesser

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [372]:
A = np.random.randint(0, 2, (20, 3))
print(A)
np.unique(A, axis=0)

[[0 1 0]
 [1 1 1]
 [1 0 1]
 [1 0 0]
 [0 1 0]
 [1 0 1]
 [1 1 1]
 [0 1 0]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [0 1 0]
 [0 1 0]
 [1 1 0]
 [0 1 1]
 [0 0 1]
 [1 1 1]
 [1 1 1]
 [1 0 1]
 [0 0 1]]


array([[0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [409]:
A = np.arange(0, 4)
B = np.arange(0, 4)
print(np.einsum("i, i ->", A, B))
print(np.einsum("i, j -> ij", A, B))
print(np.einsum("i ->", A) + np.einsum("i ->", B))
print(np.einsum("i, i -> i", A, B))

14
[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]
12
[0 1 4 9]


In [393]:
hint(97)

hint: np.einsum


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [418]:
A = np.arange(0, 100)
X = A.copy()
Y = X ** 2
x = np.array([3, 5])
np.interp(x, X, Y)


array([ 9., 25.])

In [412]:
hint(98)

hint: np.cumsum, np.interp


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [441]:
X = np.random.randint(0, 5, (10, 3))
print(X)
n = 8 
A = (np.sum(X, axis=1) == 8) & np.all(np.mod(X, 1) == 0)
print(A)
X[A]



[[4 1 2]
 [2 3 0]
 [2 2 2]
 [1 3 0]
 [2 0 2]
 [1 2 4]
 [2 1 0]
 [1 2 3]
 [4 3 4]
 [2 4 2]]
[False False False False False False False False False  True]


array([[2, 4, 2]])

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)