# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [281]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [282]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [283]:
print(np.__version__)

1.26.4


#### 3. Create a null vector of size 10 (★☆☆)

In [284]:
a = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [285]:
a.nbytes
answer(4)

Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [286]:
# help(np.add)
answer(5)

%run `python -c "import numpy; numpy.info(numpy.add)"`


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [287]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [288]:
answer(6)

Z = np.zeros(10)
Z[4] = 1
print(Z)


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [289]:
a = np.random.randint(10, 50, 10)
a


array([37, 28, 36, 38, 43, 49, 29, 23, 25, 21])

In [290]:
answer(7)

Z = np.arange(10,50)
print(Z)


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [291]:
a[::-1]

array([21, 25, 23, 29, 49, 43, 38, 36, 28, 37])

In [292]:
answer(8)

Z = np.arange(50)
Z = Z[::-1]
print(Z)


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [293]:
a = np.random.randint(0, 9, 9).reshape(3, 3)
a

array([[3, 6, 4],
       [0, 3, 4],
       [0, 5, 8]])

In [294]:
answer(9)

Z = np.arange(9).reshape(3, 3)
print(Z)


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [295]:
a = np.array([1, 2, 0, 0, 4, 0])
a = np.where(a == 0)
a

(array([2, 3, 5], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [296]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [297]:
np.random.random([3, 3, 3])

array([[[0.27293426, 0.86299296, 0.45879503],
        [0.7821903 , 0.13660711, 0.85532354],
        [0.04204933, 0.18541007, 0.65843443]],

       [[0.29869553, 0.03382816, 0.93976025],
        [0.92683192, 0.09050031, 0.72232995],
        [0.55891514, 0.45108427, 0.30304608]],

       [[0.44052956, 0.51226847, 0.07552396],
        [0.05515063, 0.16703041, 0.31593106],
        [0.52511098, 0.22851678, 0.63277314]]])

In [298]:
answer(12)

Z = np.random.random((3,3,3))
print(Z)


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [299]:
a = np.random.random([10, 10])
print(a.min(), a.max())

0.033780564788302714 0.957817393021751


In [300]:
answer(13)

Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [301]:
a = np.random.random(30).mean()
print(a)

0.5780622913434372


In [302]:
answer(14)

Z = np.random.random(30)
m = Z.mean()
print(m)


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [303]:
a = np.ones([4, 4])
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [304]:
answer(15)

Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [305]:
a = np.ones([3, 3])
a = np.pad(a, pad_width=1, mode="constant")  # padding
a

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [306]:
answer(16)

Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [307]:
0.3 == 3 * 0.1

False

In [308]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [309]:
answer(17)

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [310]:
np.diag([1, 2, 3, 4], k=0)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [311]:
a = np.zeros([8, 8])
a[::2, ::2] = 1
a[1::2, 1::2] = 1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [312]:
a = np.array(np.arange(336).reshape(6, 7, 8))
a[1, 5, 3]

99

In [313]:
print(np.unravel_index(99,(6,7,8)))  # 1次元のインデックスを多次元インデックスに変換してくれる

(1, 5, 3)


In [314]:
answer(20)

print(np.unravel_index(99,(6,7,8)))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [315]:
a = [[0, 1], [1, 0]]
b = np.tile(a, (4, 4))
b

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [316]:
answer(21)

Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [317]:
a = np.array(np.random.random((5, 5)))
a_min = a.min()
a_max = a.max()
a = (a - a_min) / (a_max - a_min)
a


array([[0.48607008, 0.48141461, 0.56994502, 0.52890771, 0.74264784],
       [0.84247449, 0.06388921, 0.52866325, 0.9600588 , 0.92083011],
       [0.80997032, 0.48473022, 0.07594843, 0.33798513, 0.        ],
       [0.31226404, 0.2717121 , 0.32663348, 0.59043074, 0.3213757 ],
       [0.40527485, 0.30520119, 0.91588735, 0.71761053, 1.        ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [318]:
color = np.dtype([("r", np.ubyte),
                 ("g", np.ubyte),
                 ("b", np.ubyte),
                 ("a", np.ubyte)])

In [319]:
answer(23)

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [320]:
a = np.array(np.random.random([5, 3]))
b = np.array(np.random.random([3, 2]))
np.matmul(a, b)

array([[0.27874309, 0.0259573 ],
       [2.11151459, 0.33841345],
       [0.66105093, 0.08452686],
       [1.30407826, 0.21787966],
       [1.50081306, 0.25303032]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [321]:
a = np.array(np.arange(11))
a[((3 < a) & (a < 8))] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

In [322]:
answer(25)

# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)


In [323]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [324]:
sum(range(5), -1)

9

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [325]:
####
"""python
1. ok
2. no
3. ok
4. ok
5. ok
6. no
"""

'python\n1. ok\n2. no\n3. ok\n4. ok\n5. ok\n6. no\n'

In [326]:
Z = np.array([1, 2, 3])
1j*Z  # jは虚数単位

array([0.+1.j, 0.+2.j, 0.+3.j])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [327]:
np.array(0) / np.array(0)  # numpyはエラーが出たときに中断せずに、nanを返す

nan

In [328]:
np.array(0) // np.array(0)

0

In [329]:
np.array([np.nan]).astype(int).astype(float)  # np.nanはint型に変えるとその方の最小値になる

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [330]:
a = np.array(np.random.uniform(-10, 10, 5))
print(a)
a = np.where(a >= 0, np.ceil(a), np.floor(a))
print(a)

[ 4.85720838 -2.51068875  9.96473478  4.66300342 -7.48921298]
[ 5. -3. 10.  5. -8.]


In [331]:
answer(29)

# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))


#### 30. How to find common values between two arrays? (★☆☆)

In [332]:
a = np.random.randint(1, 9, 5)
b = np.random.randint(1, 9, 5)
print(a, b)
np.intersect1d(a, b)  # 共通の値を出力する, 出力はsortされている

[8 8 7 1 2] [4 5 3 3 7]


array([7])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [333]:
answer(31)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


In [334]:
defaults = np.seterr(all="ignore")
z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [335]:
np.emath.sqrt(-1)  # emathは複素数が答えの場合は複素数に変える

1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [336]:
print(np.datetime64("today", "D") - np.timedelta64(1, "D"))
print(np.datetime64("today", "D"))
print(np.datetime64("today", "D") + np.timedelta64(1, "D"))

2025-06-16
2025-06-17
2025-06-18


In [337]:
import pandas as pd

today = pd.Timestamp("today")
yesterday = (today - pd.Timedelta(days=1)).strftime("%Y-%m-%d")
tomorrow = (today + pd.Timedelta(days=1)).strftime("%Y-%m-%d")
today = today.strftime("%Y-%m-%d")
print(yesterday, today, tomorrow)

2025-06-16 2025-06-17 2025-06-18


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [338]:
a = pd.date_range(start="2016-07-01", end="2016-07-31", freq="D")
a

DatetimeIndex(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
               '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
               '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
               '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
               '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
               '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
               '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
               '2016-07-29', '2016-07-30', '2016-07-31'],
              dtype='datetime64[ns]', freq='D')

In [339]:
np.arange("2016-07", "2016-08", dtype="datetime64[D]")

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [340]:
answer(34)

Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [341]:
answer(35)

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


In [342]:
A = np.ones(3) * 1
B = np.ones(3) * 2
print(B)
print(np.add(A, B, out=B))  # numpyのaddやnegativeを使うことによってメモリの使用を削減できる
np.negative(A, out=A)
print(np.divide(A, 2, out=A))

[2. 2. 2.]
[3. 3. 3.]
[-0.5 -0.5 -0.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [343]:
a = np.array([9.43702508, 5.44392995, -8.80030341, -4.46399976, -1.06240269])
print(a.astype(int))
print(np.where(a >= 0, np.floor(a), np.ceil(a)))
print(a // 1)
print(np.trunc(a))  # np.where(a >= 0, np.floor(a), np.ceil(a))これと同じ

[ 9  5 -8 -4 -1]
[ 9.  5. -8. -4. -1.]
[ 9.  5. -9. -5. -2.]
[ 9.  5. -8. -4. -1.]


In [344]:
answer(36)

Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [345]:
np.array(np.tile([0, 1, 2, 3, 4], (5, 1)))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [346]:
answer(37)

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [347]:
def int_generator():
    for i in range(10):
        yield i

print(np.fromiter(int_generator(), dtype=int))

[0 1 2 3 4 5 6 7 8 9]


In [348]:
answer(38)

def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [349]:
np.nextafter(0, 1)

5e-324

In [350]:
np.random.uniform(np.nextafter(0, 1), 1, 10)

array([0.60580342, 0.00751403, 0.99494695, 0.2237319 , 0.28249622,
       0.87595581, 0.94437523, 0.89350509, 0.01760866, 0.30299832])

In [351]:
np.linspace(0, 1, 11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [352]:
answer(39)

Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [353]:
a = np.random.random(10)
a.sort()
print(a)

[0.05772134 0.13790262 0.23507888 0.2493992  0.37205052 0.37876089
 0.57351867 0.89876865 0.90202206 0.94686941]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [354]:
answer(41)

# Author: Evgeni Burovski

Z = np.arange(10)
np.add.reduce(Z)


In [355]:
a = np.arange(10)
np.add.reduce(a)

45

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [356]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
equal = np.allclose(A, B)
print(equal)

False


In [357]:
answer(42)

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)


#### 43. Make an array immutable (read-only) (★★☆)

In [358]:
a = np.array([1, 2, 3])
a.flags.writeable = False
a

array([1, 2, 3])

In [359]:
answer(43)

Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [360]:
A = np.array([[0.16702026, 0.17824744],
 [0.66112783, 0.93869856],
 [0.67644807, 0.3256588 ],
 [0.24854642, 0.58445634],
 [0.0551434, 0.4596011 ],
 [0.49144912, 0.17056799],
 [0.86365082, 0.42253366],
 [0.49300285, 0.74969368],
 [0.5517937, 0.35342211],
 [0.33419615, 0.939642]])
sheta = np.arctan2(A[:, 1] ,A[:, 0])
np.square(A, out=A)
A = np.sum(A, axis=1)
R = np.sqrt(A)
print(R)
print(sheta)


[0.24427017 1.14814851 0.75075672 0.63510986 0.46289736 0.52020734
 0.96147149 0.89726943 0.65527359 0.99730344]
[0.81790403 0.95718855 0.44867724 1.16870473 1.45138613 0.33406354
 0.45500367 0.98909295 0.56966557 1.22908521]


In [361]:
Z = np.random.random((10,2))
print(Z)
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[[0.79614336 0.14310311]
 [0.32525926 0.14302375]
 [0.71824156 0.7027023 ]
 [0.06795029 0.73293216]
 [0.06027205 0.35329196]
 [0.56160972 0.39831783]
 [0.34795989 0.93975388]
 [0.83228044 0.05070296]
 [0.20714397 0.93866153]
 [0.06620333 0.18040564]]
[0.80890219 0.35531588 1.00481912 0.73607527 0.35839633 0.68852202
 1.00210451 0.83382344 0.96124612 0.19216939]
[0.17784632 0.41427418 0.77446273 1.47835039 1.40182187 0.6169025
 1.21618154 0.06084532 1.35359736 1.21908478]


In [362]:
answer(44)

Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [363]:
a = np.random.random(10)
a[a.argmax()] = 0
a

array([0.11507842, 0.        , 0.03021696, 0.77512511, 0.75689049,
       0.77541808, 0.75412942, 0.73081787, 0.05364214, 0.28608749])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [364]:
structed_dtype = np.dtype([("x", float), ("y", float)])
a = np.array(np.random.uniform(0, np.nextafter(1, 2), 10).reshape(-1, 2))
a.dtype = structed_dtype
a

array([[(0.67852026, 0.54770659)],
       [(0.64782289, 0.36613246)],
       [(0.37850801, 0.88640785)],
       [(0.90040618, 0.55149932)],
       [(0.49389828, 0.24173584)]], dtype=[('x', '<f8'), ('y', '<f8')])

In [365]:
answer(46)

Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [366]:
X = np.array(np.random.random(5))
Y = np.array(np.random.random(5))
C = 1 / np.subtract.outer(X, Y)
print(C)

[[ -1.8294197   -1.84817588 -11.6012579   87.86656219  -4.19260423]
 [ 73.63925675  52.28187078   2.10968868   1.74953016   3.10862245]
 [ -1.41022293  -1.42134214  -4.02116952  -6.61789598  -2.49375588]
 [ -3.42873082  -3.49521134   5.92519683   3.75446959  60.77891325]
 [ -2.94122762  -2.99001295   8.30359365   4.58698283 -31.35985288]]


In [367]:
answer(47)

# Author: Evgeni Burovski

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))


In [368]:
a = np.array(np.random.randint(1, 10, 10))
b = np.array(np.random.randint(1, 10, 3))
np.add.outer(a, b)

array([[13, 12,  9],
       [17, 16, 13],
       [14, 13, 10],
       [13, 12,  9],
       [18, 17, 14],
       [16, 15, 12],
       [13, 12,  9],
       [13, 12,  9],
       [12, 11,  8],
       [18, 17, 14]])

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [369]:
print(np.iinfo(np.int8))
print(np.finfo(np.float16))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for float16
---------------------------------------------------------------
precision =   3   resolution = 1.00040e-03
machep =    -10   eps =        9.76562e-04
negep =     -11   epsneg =     4.88281e-04
minexp =    -14   tiny =       6.10352e-05
maxexp =     16   max =        6.55040e+04
nexp =        5   min =        -max
smallest_normal = 6.10352e-05   smallest_subnormal = 5.96046e-08
---------------------------------------------------------------



In [370]:
hint(48)

hint: np.iinfo, np.finfo, eps


#### 49. How to print all the values of an array? (★★☆)

In [371]:
np.set_printoptions(threshold=float("inf"))
# np.set_printoptions(threshold=1000)
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [372]:
hint(49)

hint: np.set_printoptions


In [373]:
answer(49)

np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [374]:
a = np.arange(100)
v = np.random.uniform(0, 100)
index = np.abs(np.subtract(a, v)).argmin()
a[index]

28

In [375]:
answer(50)

Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
a = np.zeros(2, dtype=[("position", [("x", float, 1),
                                      ("y", float, 1)]),
                        ("color", [("r", float, 1),
                                   ("g", float, 1),
                                   ("b", float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\CHU1P\AppData\Local\Temp\ipykernel_30360\4134159954.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = np.zeros(2, dtype=[("position", [("x", float, 1),


In [378]:
answer(51)

Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [411]:
a = np.random.random((10,2))
delta_coords = a[:, np.newaxis, :] - a[np.newaxis, :, :]
r = np.sqrt(np.sum(np.square(delta_coords), axis=2))
print(r[:5])

[[0.         0.25615834 0.23170807 0.50448252 0.4366178  0.40192567
  0.87439171 0.63909016 0.84115569 0.3742821 ]
 [0.25615834 0.         0.26381422 0.37474433 0.49092051 0.21098238
  0.75608334 0.39253473 0.62647618 0.61483519]
 [0.23170807 0.26381422 0.         0.29585794 0.23501683 0.26067308
  0.647932   0.5328183  0.67167625 0.43583563]
 [0.50448252 0.37474433 0.29585794 0.         0.32916192 0.17712168
  0.38368934 0.35573408 0.39360666 0.71516439]
 [0.4366178  0.49092051 0.23501683 0.32916192 0.         0.41142681
  0.55048208 0.66619772 0.71450647 0.45575283]]


In [ ]:
a[:, np.newaxis, :] - a[np.newaxis, :, :]

In [421]:
Z = np.random.random((10,2))
X,Y = Z[:, np.newaxis, 0], Z[:, np.newaxis, 1]
D = np.sqrt((X - X.T)**2 + (Y - Y.T)**2)
print(D)

[[0.         0.14352964 0.58767184 0.77256304 0.39864776 0.20521545
  0.54275196 0.51824636 0.66598913 0.03049023]
 [0.14352964 0.         0.56176312 0.73405378 0.3753811  0.09240852
  0.53094561 0.37781521 0.56988953 0.1427536 ]
 [0.58767184 0.56176312 0.         0.18913112 0.19005621 0.48043092
  0.06699288 0.57650401 0.32728568 0.55765206]
 [0.77256304 0.73405378 0.18913112 0.         0.37405227 0.64740945
  0.24874711 0.67376718 0.34030915 0.74291118]
 [0.39864776 0.3753811  0.19005621 0.37405227 0.         0.29961662
  0.15606454 0.47082699 0.36013919 0.36889708]
 [0.20521545 0.09240852 0.48043092 0.64740945 0.29961662 0.
  0.45547974 0.32158134 0.47844782 0.19145775]
 [0.54275196 0.53094561 0.06699288 0.24874711 0.15606454 0.45547974
  0.         0.58988646 0.37698236 0.51237363]
 [0.51824636 0.37781521 0.57650401 0.67376718 0.47082699 0.32158134
  0.58988646 0.         0.36531638 0.50979439]
 [0.66598913 0.56988953 0.32728568 0.34030915 0.36013919 0.47844782
  0.37698236 0.36531

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)