# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)

1.26.4


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
a = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [6]:
a.nbytes
answer(4)

Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
# help(np.add)
answer(5)

%run `python -c "import numpy; numpy.info(numpy.add)"`


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [9]:
answer(6)

Z = np.zeros(10)
Z[4] = 1
print(Z)


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
a = np.random.randint(10, 50, 10)
a


array([17, 33, 33, 39, 11, 35, 36, 18, 14, 19])

In [11]:
answer(7)

Z = np.arange(10,50)
print(Z)


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [12]:
a[::-1]

array([19, 14, 18, 36, 35, 11, 39, 33, 33, 17])

In [13]:
answer(8)

Z = np.arange(50)
Z = Z[::-1]
print(Z)


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [14]:
a = np.random.randint(0, 9, 9).reshape(3, 3)
a

array([[8, 2, 5],
       [8, 1, 6],
       [6, 5, 4]])

In [15]:
answer(9)

Z = np.arange(9).reshape(3, 3)
print(Z)


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [16]:
a = np.array([1, 2, 0, 0, 4, 0])
a = np.where(a == 0)
a

(array([2, 3, 5], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [17]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [18]:
np.random.random([3, 3, 3])

array([[[0.57877444, 0.35463001, 0.61294869],
        [0.36166685, 0.44043002, 0.08255415],
        [0.84502697, 0.2049195 , 0.92042173]],

       [[0.87847905, 0.9642972 , 0.79762479],
        [0.20266408, 0.52700992, 0.43551034],
        [0.32240374, 0.35447026, 0.23100314]],

       [[0.99230204, 0.08835894, 0.42732924],
        [0.75121061, 0.02621785, 0.78419463],
        [0.01145151, 0.43408476, 0.88851372]]])

In [19]:
answer(12)

Z = np.random.random((3,3,3))
print(Z)


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [20]:
a = np.random.random([10, 10])
print(a.min(), a.max())

0.014457339061302754 0.9939396684132791


In [21]:
answer(13)

Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [22]:
a = np.random.random(30).mean()
print(a)

0.49344355206179785


In [23]:
answer(14)

Z = np.random.random(30)
m = Z.mean()
print(m)


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [24]:
a = np.ones([4, 4])
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [25]:
answer(15)

Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [26]:
a = np.ones([3, 3])
a = np.pad(a, pad_width=1, mode="constant")  # padding
a

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
answer(16)

Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [28]:
0.3 == 3 * 0.1

False

In [29]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [30]:
answer(17)

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [31]:
np.diag([1, 2, 3, 4], k=0)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [32]:
a = np.zeros([8, 8])
a[::2, ::2] = 1
a[1::2, 1::2] = 1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [33]:
a = np.array(np.arange(336).reshape(6, 7, 8))
a[1, 5, 3]

99

In [34]:
print(np.unravel_index(99,(6,7,8)))  # 1次元のインデックスを多次元インデックスに変換してくれる

(1, 5, 3)


In [35]:
answer(20)

print(np.unravel_index(99,(6,7,8)))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [36]:
a = [[0, 1], [1, 0]]
b = np.tile(a, (4, 4))
b

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [37]:
answer(21)

Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [38]:
a = np.array(np.random.random((5, 5)))
a_min = a.min()
a_max = a.max()
a = (a - a_min) / (a_max - a_min)
a


array([[0.19895754, 0.81399299, 0.45759227, 0.16097013, 0.91323762],
       [0.17104304, 0.59279423, 0.06069532, 0.98860049, 0.17111443],
       [0.39854273, 0.59004097, 1.        , 0.14899289, 0.7356448 ],
       [0.2477074 , 0.93460239, 0.55931621, 0.24934014, 0.1855291 ],
       [0.31807513, 0.67349641, 0.87042532, 0.        , 0.94663951]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [39]:
color = np.dtype([("r", np.ubyte),
                 ("g", np.ubyte),
                 ("b", np.ubyte),
                 ("a", np.ubyte)])

In [40]:
answer(23)

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [41]:
a = np.array(np.random.random([5, 3]))
b = np.array(np.random.random([3, 2]))
np.matmul(a, b)

array([[0.79798134, 0.93271472],
       [0.8030728 , 0.5512972 ],
       [0.66857071, 0.76420499],
       [0.82695298, 0.76815388],
       [0.71552017, 0.50530986]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [42]:
a = np.array(np.arange(11))
a[((3 < a) & (a < 8))] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

In [43]:
answer(25)

# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)


In [44]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [45]:
sum(range(5), -1)

9

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [46]:
####
"""python
1. ok
2. no
3. ok
4. ok
5. ok
6. no
"""

'python\n1. ok\n2. no\n3. ok\n4. ok\n5. ok\n6. no\n'

In [47]:
Z = np.array([1, 2, 3])
1j*Z  # jは虚数単位

array([0.+1.j, 0.+2.j, 0.+3.j])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [48]:
np.array(0) / np.array(0)  # numpyはエラーが出たときに中断せずに、nanを返す

C:\Users\CHU1P\AppData\Local\Temp\ipykernel_9888\941235769.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)  # numpyはエラーが出たときに中断せずに、nanを返す


nan

In [49]:
np.array(0) // np.array(0)

C:\Users\CHU1P\AppData\Local\Temp\ipykernel_9888\2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [50]:
np.array([np.nan]).astype(int).astype(float)  # np.nanはint型に変えるとその方の最小値になる

C:\Users\CHU1P\AppData\Local\Temp\ipykernel_9888\2424127791.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)  # np.nanはint型に変えるとその方の最小値になる


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [51]:
a = np.array(np.random.uniform(-10, 10, 5))
print(a)
a = np.where(a >= 0, np.ceil(a), np.floor(a))
print(a)

[-4.8779126   1.05742964  9.78789253 -8.83080269  3.32605847]
[-5.  2. 10. -9.  4.]


In [52]:
answer(29)

# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))


#### 30. How to find common values between two arrays? (★☆☆)

In [53]:
a = np.random.randint(1, 9, 5)
b = np.random.randint(1, 9, 5)
print(a, b)
np.intersect1d(a, b)  # 共通の値を出力する, 出力はsortされている

[5 8 7 4 3] [2 3 5 4 1]


array([3, 4, 5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [54]:
answer(31)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


In [55]:
defaults = np.seterr(all="ignore")
z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [56]:
np.emath.sqrt(-1)  # emathは複素数が答えの場合は複素数に変える

1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [57]:
print(np.datetime64("today", "D") - np.timedelta64(1, "D"))
print(np.datetime64("today", "D"))
print(np.datetime64("today", "D") + np.timedelta64(1, "D"))

2025-06-25
2025-06-26
2025-06-27


In [58]:
import pandas as pd

today = pd.Timestamp("today")
yesterday = (today - pd.Timedelta(days=1)).strftime("%Y-%m-%d")
tomorrow = (today + pd.Timedelta(days=1)).strftime("%Y-%m-%d")
today = today.strftime("%Y-%m-%d")
print(yesterday, today, tomorrow)

2025-06-25 2025-06-26 2025-06-27


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [59]:
a = pd.date_range(start="2016-07-01", end="2016-07-31", freq="D")
a

DatetimeIndex(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
               '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
               '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
               '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
               '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
               '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
               '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
               '2016-07-29', '2016-07-30', '2016-07-31'],
              dtype='datetime64[ns]', freq='D')

In [60]:
np.arange("2016-07", "2016-08", dtype="datetime64[D]")

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [61]:
answer(34)

Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [62]:
answer(35)

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


In [63]:
A = np.ones(3) * 1
B = np.ones(3) * 2
print(B)
print(np.add(A, B, out=B))  # numpyのaddやnegativeを使うことによってメモリの使用を削減できる
np.negative(A, out=A)
print(np.divide(A, 2, out=A))

[2. 2. 2.]
[3. 3. 3.]
[-0.5 -0.5 -0.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [64]:
a = np.array([9.43702508, 5.44392995, -8.80030341, -4.46399976, -1.06240269])
print(a.astype(int))
print(np.where(a >= 0, np.floor(a), np.ceil(a)))
print(a // 1)
print(np.trunc(a))  # np.where(a >= 0, np.floor(a), np.ceil(a))これと同じ

[ 9  5 -8 -4 -1]
[ 9.  5. -8. -4. -1.]
[ 9.  5. -9. -5. -2.]
[ 9.  5. -8. -4. -1.]


In [65]:
answer(36)

Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [66]:
np.array(np.tile([0, 1, 2, 3, 4], (5, 1)))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [67]:
answer(37)

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [68]:
def int_generator():
    for i in range(10):
        yield i

print(np.fromiter(int_generator(), dtype=int))

[0 1 2 3 4 5 6 7 8 9]


In [69]:
answer(38)

def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [70]:
np.nextafter(0, 1)

5e-324

In [71]:
np.random.uniform(np.nextafter(0, 1), 1, 10)

array([0.78508794, 0.91948423, 0.41128446, 0.39920711, 0.13452403,
       0.07364667, 0.33555575, 0.51505447, 0.97096971, 0.38526793])

In [72]:
np.linspace(0, 1, 11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [73]:
answer(39)

Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [74]:
a = np.random.random(10)
a.sort()
print(a)

[0.01928517 0.04735718 0.20045512 0.22555198 0.36110076 0.36444423
 0.47535693 0.60637293 0.70957414 0.86794302]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [75]:
answer(41)

# Author: Evgeni Burovski

Z = np.arange(10)
np.add.reduce(Z)


In [76]:
a = np.arange(10)
np.add.reduce(a)

45

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [77]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
equal = np.allclose(A, B)
print(equal)

False


In [78]:
answer(42)

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)


#### 43. Make an array immutable (read-only) (★★☆)

In [79]:
a = np.array([1, 2, 3])
a.flags.writeable = False
a

array([1, 2, 3])

In [80]:
answer(43)

Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [81]:
A = np.array([[0.16702026, 0.17824744],
 [0.66112783, 0.93869856],
 [0.67644807, 0.3256588 ],
 [0.24854642, 0.58445634],
 [0.0551434, 0.4596011 ],
 [0.49144912, 0.17056799],
 [0.86365082, 0.42253366],
 [0.49300285, 0.74969368],
 [0.5517937, 0.35342211],
 [0.33419615, 0.939642]])
sheta = np.arctan2(A[:, 1] ,A[:, 0])
np.square(A, out=A)
A = np.sum(A, axis=1)
R = np.sqrt(A)
print(R)
print(sheta)


[0.24427017 1.14814851 0.75075672 0.63510986 0.46289736 0.52020734
 0.96147149 0.89726943 0.65527359 0.99730344]
[0.81790403 0.95718855 0.44867724 1.16870473 1.45138613 0.33406354
 0.45500367 0.98909295 0.56966557 1.22908521]


In [82]:
Z = np.random.random((10,2))
print(Z)
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[[0.03189334 0.79305248]
 [0.72734339 0.98310595]
 [0.92951647 0.92876944]
 [0.07514887 0.82878422]
 [0.79224423 0.5981162 ]
 [0.82816647 0.39282688]
 [0.78586374 0.4554756 ]
 [0.07524475 0.20108279]
 [0.78948221 0.91160702]
 [0.67455952 0.75173031]]
[0.79369354 1.22291689 1.31400667 0.83218426 0.99267009 0.91660933
 0.90831703 0.21469993 1.20594757 1.01001436]
[1.53060206 0.93382789 0.78499616 1.48036998 0.64667077 0.44290418
 0.52527393 1.21272908 0.85706733 0.83945142]


In [83]:
answer(44)

Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [84]:
a = np.random.random(10)
a[a.argmax()] = 0
a

array([0.        , 0.29982553, 0.22537071, 0.84702274, 0.78513733,
       0.06814911, 0.45699732, 0.43298282, 0.349933  , 0.06794928])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [85]:
structed_dtype = np.dtype([("x", float), ("y", float)])
a = np.array(np.random.uniform(0, np.nextafter(1, 2), 10).reshape(-1, 2))
a.dtype = structed_dtype
a

array([[(0.03296376, 0.5266849 )],
       [(0.77853777, 0.07895188)],
       [(0.92018856, 0.47922308)],
       [(0.4407441 , 0.4140459 )],
       [(0.05935916, 0.04859092)]], dtype=[('x', '<f8'), ('y', '<f8')])

In [86]:
answer(46)

Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [87]:
X = np.array(np.random.random(5))
Y = np.array(np.random.random(5))
C = 1 / np.subtract.outer(X, Y)
print(C)

[[   1.07390596    1.34056591    7.57855676    1.56426045    1.16520926]
 [   2.41131041    4.35757069   -2.60066715    8.14254219    2.92614145]
 [   3.44735903    9.53738668   -1.96405058 -548.4348157     4.60592106]
 [   2.01948705    3.22634091   -3.28889233    4.91945013    2.36848982]
 [   1.84882917    2.8117037    -3.870776      4.01634884    2.13712856]]


In [88]:
answer(47)

# Author: Evgeni Burovski

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))


In [89]:
a = np.array(np.random.randint(1, 10, 10))
b = np.array(np.random.randint(1, 10, 3))
np.add.outer(a, b)

array([[12, 12, 11],
       [10, 10,  9],
       [16, 16, 15],
       [17, 17, 16],
       [10, 10,  9],
       [12, 12, 11],
       [10, 10,  9],
       [ 9,  9,  8],
       [13, 13, 12],
       [11, 11, 10]])

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [90]:
print(np.iinfo(np.int8))
print(np.finfo(np.float16))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for float16
---------------------------------------------------------------
precision =   3   resolution = 1.00040e-03
machep =    -10   eps =        9.76562e-04
negep =     -11   epsneg =     4.88281e-04
minexp =    -14   tiny =       6.10352e-05
maxexp =     16   max =        6.55040e+04
nexp =        5   min =        -max
smallest_normal = 6.10352e-05   smallest_subnormal = 5.96046e-08
---------------------------------------------------------------



In [91]:
hint(48)

hint: np.iinfo, np.finfo, eps


#### 49. How to print all the values of an array? (★★☆)

In [92]:
np.set_printoptions(threshold=float("inf"))
# np.set_printoptions(threshold=1000)
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [93]:
hint(49)

hint: np.set_printoptions


In [94]:
answer(49)

np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [95]:
a = np.arange(100)
v = np.random.uniform(0, 100)
index = np.abs(np.subtract(a, v)).argmin()
a[index]

87

In [96]:
answer(50)

Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [97]:
a = np.zeros(2, dtype=[("position", [("x", float, 1),
                                      ("y", float, 1)]),
                        ("color", [("r", float, 1),
                                   ("g", float, 1),
                                   ("b", float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\CHU1P\AppData\Local\Temp\ipykernel_9888\4134159954.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = np.zeros(2, dtype=[("position", [("x", float, 1),


In [98]:
answer(51)

Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [99]:
a = np.random.random((10,2))
delta_coords = a[:, np.newaxis, :] - a[np.newaxis, :, :]
r = np.sqrt(np.sum(np.square(delta_coords), axis=2))
print(r[:5])

[[0.         0.42094242 0.50402543 0.27648791 0.51504539 0.28263877
  0.39173594 0.11352866 0.64647191 0.31298064]
 [0.42094242 0.         0.09472237 0.50708752 0.87862474 0.18423334
  0.20578956 0.5111526  0.59937066 0.5356793 ]
 [0.50402543 0.09472237 0.         0.60178685 0.97223127 0.27895296
  0.21228057 0.58671173 0.66996237 0.57876697]
 [0.27648791 0.50708752 0.60178685 0.         0.39161388 0.3228852
  0.58131806 0.36126331 0.41781635 0.58920569]
 [0.51504539 0.87862474 0.97223127 0.39161388 0.         0.69778562
  0.90231231 0.51251859 0.71584583 0.74939981]]


In [100]:
a[:, np.newaxis, :] - a[np.newaxis, :, :]

array([[[ 0.        ,  0.        ],
        [ 0.1007055 , -0.40871864],
        [ 0.16826915, -0.47510749],
        [-0.2694231 , -0.06210276],
        [-0.41869267,  0.299947  ],
        [-0.03190992, -0.28083168],
        [ 0.26663267, -0.28699141],
        [ 0.05331294,  0.10023217],
        [-0.49865909, -0.41141833],
        [ 0.30023291,  0.08841427]],

       [[-0.1007055 ,  0.40871864],
        [ 0.        ,  0.        ],
        [ 0.06756365, -0.06638885],
        [-0.3701286 ,  0.34661588],
        [-0.51939817,  0.70866564],
        [-0.13261542,  0.12788696],
        [ 0.16592717,  0.12172723],
        [-0.04739256,  0.50895081],
        [-0.59936458, -0.00269969],
        [ 0.19952741,  0.49713291]],

       [[-0.16826915,  0.47510749],
        [-0.06756365,  0.06638885],
        [ 0.        ,  0.        ],
        [-0.43769225,  0.41300473],
        [-0.58696182,  0.77505449],
        [-0.20017907,  0.19427581],
        [ 0.09836352,  0.18811608],
        [-0.11495621,  0

In [101]:
Z = np.random.random((10,2))
X,Y = Z[:, np.newaxis, 0], Z[:, np.newaxis, 1]
D = np.sqrt((X - X.T)**2 + (Y - Y.T)**2)
print(D)

[[0.         1.14455319 0.4095388  0.48080931 0.67076248 0.95305872
  0.62766723 0.24928063 0.90552768 0.97253969]
 [1.14455319 0.         0.90223989 0.69670589 0.56021133 0.25367511
  0.66725877 0.89684543 0.34554386 0.61345401]
 [0.4095388  0.90223989 0.         0.2299335  0.34768806 0.6654786
  0.64646021 0.31676996 0.77834451 0.57958832]
 [0.48080931 0.69670589 0.2299335  0.         0.19263452 0.47999684
  0.4473713  0.26689254 0.54845633 0.52726868]
 [0.67076248 0.56021133 0.34768806 0.19263452 0.         0.31800591
  0.53444391 0.45806671 0.50943259 0.35116157]
 [0.95305872 0.25367511 0.6654786  0.47999684 0.31800591 0.
  0.59921268 0.71494062 0.37686201 0.3888401 ]
 [0.62766723 0.66725877 0.64646021 0.4473713  0.53444391 0.59921268
  0.         0.41028406 0.33861743 0.86736747]
 [0.24928063 0.89684543 0.31676996 0.26689254 0.45806671 0.71494062
  0.41028406 0.         0.65991096 0.79148076]
 [0.90552768 0.34554386 0.77834451 0.54845633 0.50943259 0.37686201
  0.33861743 0.659910

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [102]:
A = np.random.randn(10)
print(A)
# A[:]とすることでAの要素だけを書き換えれる
A[:] = A.astype(np.int32)
print(A)

[ 1.19948121 -0.26569869 -1.79508178 -0.36713315  0.61227957  0.40911176
  0.20268907  0.84615218 -1.35647375  1.07008812]
[ 1.  0. -1.  0.  0.  0.  0.  0. -1.  1.]


In [103]:
answer(53)

# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [104]:
hint(54)

hint: np.genfromtxt


In [105]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5
             6, , , 7, 8
              , , 9,10,11""")
data = np.genfromtxt(s, delimiter=",", dtype=float)
data


array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

In [106]:
from io import StringIO
import pandas as pd

s = StringIO("""1, 2, 3, 4, 5
6, , , 7, 8
 , , 9,10,11""")
data = pd.read_csv(s, sep=",", header=None, na_values=[" "])
print(data)

     0    1    2   3   4
0  1.0  2.0  3.0   4   5
1  6.0  NaN  NaN   7   8
2  NaN  NaN  9.0  10  11


In [107]:
answer(54)

from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [108]:
A = np.array([[1, 2], [3, 4]])
for idx, val in np.ndenumerate(A):
    print(idx, val)


(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [109]:
hint(56)

hint: np.meshgrid, np.exp


In [110]:
answer(56)

X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)


In [111]:
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
D = np.sqrt(X*X + Y*Y)
sigma, mu = 1.0, 0.0
y = (np.exp(-(D - mu) / (2 * sigma)) ** 2)
print(y)

[[0.24311673 0.28171437 0.31855539 0.34850854 0.3656225  0.3656225
  0.34850854 0.31855539 0.28171437 0.24311673]
 [0.28171437 0.33288976 0.38449907 0.42904348 0.45581229 0.45581229
  0.42904348 0.38449907 0.33288976 0.28171437]
 [0.31855539 0.38449907 0.45581229 0.52315183 0.56747549 0.56747549
  0.52315183 0.45581229 0.38449907 0.31855539]
 [0.34850854 0.42904348 0.52315183 0.62412506 0.70372742 0.70372742
  0.62412506 0.52315183 0.42904348 0.34850854]
 [0.3656225  0.45581229 0.56747549 0.70372742 0.85458882 0.85458882
  0.70372742 0.56747549 0.45581229 0.3656225 ]
 [0.3656225  0.45581229 0.56747549 0.70372742 0.85458882 0.85458882
  0.70372742 0.56747549 0.45581229 0.3656225 ]
 [0.34850854 0.42904348 0.52315183 0.62412506 0.70372742 0.70372742
  0.62412506 0.52315183 0.42904348 0.34850854]
 [0.31855539 0.38449907 0.45581229 0.52315183 0.56747549 0.56747549
  0.52315183 0.45581229 0.38449907 0.31855539]
 [0.28171437 0.33288976 0.38449907 0.42904348 0.45581229 0.45581229
  0.42904348 

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [112]:
A = np.zeros((5, 5))
p = 3
idx = np.unravel_index(np.random.randint(0, 25, p, ), (5, 5))
A[idx] = 1
print(A)

[[0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [113]:
A = np.zeros((5, 5))
# choiceが重複のない選択をできる
np.put(A, np.random.choice(25, p, replace=False), 1)
print(A)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [114]:
answer(57)

# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [115]:
A = np.random.randint(0, 10, (10, 5)).astype(np.float64)
# keepdimsをしないとテンソルとして残らないため
A[:] -= np.mean(A, axis=1, keepdims=True)
print(A)

[[ 3.2  2.2  3.2 -2.8 -5.8]
 [-2.  -4.  -2.   4.   4. ]
 [-1.2 -4.2  2.8  1.8  0.8]
 [ 3.2 -1.8 -1.8  3.2 -2.8]
 [ 1.4 -1.6  3.4 -0.6 -2.6]
 [-0.6 -4.6 -0.6  3.4  2.4]
 [ 2.8 -0.2  2.8 -5.2 -0.2]
 [-0.6  0.4 -2.6  4.4 -1.6]
 [-1.2  0.8  1.8  0.8 -2.2]
 [-1.4  0.6  2.6  0.6 -2.4]]


#### 59. How to sort an array by the nth column? (★★☆)

In [116]:
A = np.random.randint(0, 10, (5, 5))
print(A)
A.argsort()
A[A[:, 1].argsort()]

[[9 7 3 0 9]
 [7 2 2 1 6]
 [3 1 0 1 2]
 [5 3 9 6 3]
 [7 8 8 9 4]]


array([[3, 1, 0, 1, 2],
       [7, 2, 2, 1, 6],
       [5, 3, 9, 6, 3],
       [9, 7, 3, 0, 9],
       [7, 8, 8, 9, 4]])

In [117]:
A = np.random.randint(0, 10, (5, 5))
print(A)
A = pd.DataFrame(A)
A.sort_values(by=1, axis=1)

[[7 0 6 9 1]
 [9 9 1 2 4]
 [5 9 5 3 7]
 [6 0 3 1 3]
 [1 1 2 7 8]]


2  3  4  0  1
0  6  9  1  7  0
1  1  2  4  9  9
2  5  3  7  5  9
3  3  1  3  6  0
4  2  7  8  1  1

In [118]:
answer(59)

# Author: Steve Tjoa

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [119]:
hint(60)

hint: any, ~


In [120]:
answer(60)

# Author: Warren Weckesser

# null : 0 
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))


In [121]:
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))
print(Z)

[False False  True]
[[ 0.  1. nan]
 [ 1.  2. nan]
 [ 4.  5. nan]]


In [122]:
Z = pd.DataFrame(Z)
# axis=Noneとすればdf全体で見てくれる
Z.isna().any(axis=0)


0    False
1    False
2     True
dtype: bool

#### 61. Find the nearest value from a given value in an array (★★☆)

In [123]:
A = np.random.rand(3, 3)
v = 7
idx = np.abs(A - v).argmin()
A[idx]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [ ]:
A = pd.DataFrame(np.random.rand(3, 3))
v = 7
A.iloc[(A - v).abs().idxmin()]

0         1         2
0  0.996294  0.222368  0.455866
2  0.516767  0.576151  0.129285
0  0.996294  0.222368  0.455866

In [ ]:
answer(61)

Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
A = np.arange(3).reshape(1, 3)
B = np.arange(3).reshape(3, 1)

it = np.nditer([A, B, None])
for x, y, z in it:
    z[...] = x + y
result = it.operands[2].reshape(3, 3)
print(result)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return
        # objにnameがあればそのままなければno nameを
        self.name = getattr(obj, "name", "no name")

A = NamedArray(np.arange(10), "range_10")
print(A.name)

range_10


In [ ]:
hint(63)

hint: class method


In [ ]:
answer(63)

class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
a = np.array([1, 2, 3, 4, 5])
i = np.array([0, 1, 1, 3])
np.add.at(a, i, 1)
print(a)

[2 4 3 5 5]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
a = np.array([1, 2, 3, 4, 5])
i = np.array([0, 1, 1, 3])
F = np.zeros(5)
np.add.at(F, i, a[i])
F

array([1., 4., 0., 4., 0.])

In [ ]:
X = [1, 2, 3, 4, 5]
I = [0, 1, 1, 3, 5]
F = np.bincount(I,X)
print(F)

[1. 5. 0. 4. 0. 5.]


In [ ]:
answer(65)

# Author: Alan G Isaac

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
answer(66)

# Author: Fisher Wang

w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

# Faster version
# Author: Mark Setchell
# https://stackoverflow.com/a/59671950/2836621

w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)


In [ ]:
np.random.randint(0, 4, (2, 3))

array([[0, 1, 3],
       [1, 0, 0]])

In [ ]:
img = np.random.randint(0, 4, (256, 256, 3)).astype(np.ubyte)
# 65536 x 3の2次元テンソルになる
colors = np.unique(img.reshape(-1, 3), axis=0)
print(colors.shape)

(64, 3)


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
A = np.array(np.random.randint(0, 10, (3, 3, 3, 3)))
A = A.sum(axis=(-2, -1))
A.shape

(3, 3)

In [ ]:
answer(67)

A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)

D_means = []
for i in range(10):
    S_idx = S == i
    D_means.append(D[S_idx].mean())
print(D_means)
    

D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

D_S = pd.DataFrame({"D": D, "S": S})
D_S.groupby("S").mean()

[0.47728775988334543, 0.47231712139565174, 0.5013878957295114, 0.7091819361054713, 0.4482493841810008, 0.7608067033595954, 0.5876007207044067, 0.46210498816823126, 0.6555768444723046, 0.5315289170977262]
[0.47728776 0.47231712 0.5013879  0.70918194 0.44824938 0.7608067
 0.58760072 0.46210499 0.65557684 0.53152892]


D
S          
0  0.477288
1  0.472317
2  0.501388
3  0.709182
4  0.448249
5  0.760807
6  0.587601
7  0.462105
8  0.655577
9  0.531529

In [ ]:
answer(68)

# Author: Jaime Fernández del Río

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A = np.random.randint(0, 10, (3, 3))
B = np.random.randint(0, 10, (3, 3,))

C = np.matmul(A, B)
print(C)
print(C.diagonal())

np.sum(A * B.T, axis=1)



[[ 30 102  33]
 [ 11  84  79]
 [ 30 138  87]]
[30 84 87]


array([30, 84, 87])

In [ ]:
answer(69)

# Author: Mathieu Blondel

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
A = np.array([1, 2, 3, 4, 5])
C = []
for a in A:
    C.append(a)
    C.extend([0, 0, 0])
print(C)

[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0]


In [ ]:
C = np.zeros(len(A) * 4, dtype=int)
C[::4] = A
print(C)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5 0 0 0]


In [ ]:
answer(70)

# Author: Warren Weckesser

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)


#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

In [ ]:
A = np.random.randint(0, 10, [5, 5, 3])
B = np.random.randint(0, 10, [5, 5])
C = A * B[:, :, np.newaxis]
print(C.shape)

(5, 5, 3)


In [ ]:
answer(71)

A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])


#### 72. How to swap two rows of an array? (★★★)

In [ ]:
A = np.arange(8).reshape(2, 4)
A[[0, 1]] = A[[1, 0]]
A


array([[4, 5, 6, 7],
       [0, 1, 2, 3]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
A = np.random.randint(0, 100, (10, 3))
F = np.roll(A.repeat(2, axis=1), -1, axis=1)
F = F.reshape(-1, 2)
F = np.sort(F, axis=1)
G = F.view(dtype=[("p0", F.dtype), ("p1", F.dtype)])
G = np.unique(G)
F = np.unique(F, axis=0)
# F = np.unique(F, axis=1)
print(F.shape)
print(G.shape)


(30, 2)
(30,)


In [ ]:
answer(73)

# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
hint(74)

hint: np.repeat


In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
A

array([1, 1, 2, 3, 4, 4, 6])

In [ ]:
answer(74)

# Author: Jaime Fernández del Río

C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
A = np.arange(7)
windows = np.lib.stride_tricks.sliding_window_view(A, window_shape=3)
windows_avg = windows.mean(axis=1)
print(windows)
print(windows_avg)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
[1. 2. 3. 4. 5.]


In [ ]:
answer(75)

# Author: Jaime Fernández del Río

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

# Author: Jeff Luo (@Jeff1999)
# make sure your NumPy >= 1.20.0

from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
A = np.arange(30)
A = np.lib.stride_tricks.sliding_window_view(A, 3)
print(A)

[[ 0  1  2]
 [ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13 14]
 [13 14 15]
 [14 15 16]
 [15 16 17]
 [16 17 18]
 [17 18 19]
 [18 19 20]
 [19 20 21]
 [20 21 22]
 [21 22 23]
 [22 23 24]
 [23 24 25]
 [24 25 26]
 [25 26 27]
 [26 27 28]
 [27 28 29]]


In [ ]:
answer(76)

# Author: Joe Kington / Erik Rigtorp
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

# Author: Jeff Luo (@Jeff1999)

Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
A = np.random.randint(0, 2, 5).astype(bool)
np.logical_not(A, out=A)
print(A)

A = np.random.uniform(-1.0, 1.0, 5)
np.negative(A, out=A)
print(A)

[False  True  True False  True]
[-0.83712563  0.35241629  0.77192229  0.05988866 -0.61954755]


In [ ]:
answer(77)

# Author: Nathaniel J. Smith

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
import numpy as np

In [ ]:
P0 = np.random.uniform(-10, 10, (10, 2))

P1 = np.random.uniform(-10, 10, (10, 2))

p = np.random.uniform(-10, 10, (1, 2))


# dx = B["x"] - A["x"]
# dy = B["y"] - A["y"]
# dydx = P1 - P0
# m = dydx[:, 0] / dydx[:, 1]
# L = np.abs(m * p[0, 0] - p[0, 1] - m * P0[:, 0] + P0[:, 1]) / np.sqrt(m ** 2 + 1)
# print(L)


a = P1 - P0
b = p - P0
# vector a の2乗
A = (a**2).sum(axis=1)
U = np.sum(a * b, axis=1) / A
H = U[:, np.newaxis] * a

dist_on = np.linalg.norm(p - (P0 + H), axis=1)
# 始点側
dist_start = np.linalg.norm(p - P0, axis=1)
# 終点側
dist_end = np.linalg.norm(p - P1, axis=1)

# 距離を場合分けで選択
distance = np.where(U < 0, dist_start,
            np.where(U > 1, dist_end, dist_on))
print(distance)


def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))


print(distance(P0, P1, p))

[ 1.02526696  4.8205729   7.39484057 12.35508469 10.65471886 10.53677457
  5.45557083 12.07359738  0.38984915  4.45133712]
[ 0.18812267  3.51849438  7.39484057 11.32699056 10.65471886  2.23519821
  4.0334612   6.51239731  0.38984915  4.45133712]


In [ ]:
answer(78)

def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10, 2))

P1 = np.random.uniform(-10, 10, (10, 2))

p = np.random.uniform(-10, 10, (5 , 2))


# dx = B["x"] - A["x"]
# dy = B["y"] - A["y"]
# dydx = P1 - P0
# m = dydx[:, 0] / dydx[:, 1]
# L = np.abs(m * p[0, 0] - p[0, 1] - m * P0[:, 0] + P0[:, 1]) / np.sqrt(m ** 2 + 1)
# print(L)


a = P1 - P0
# (10, 2) -> (1, 10, 2)
a = a[np.newaxis, :, :]
# (5, 1, 2) - (1, 10, 2) = (5, 10, 2)
b = p[:, np.newaxis, :] - P0[np.newaxis, :, :]

# vector a の2乗
# (1, 10, 2) -> (1, 10)
A = (a**2).sum(axis=2)
# (5, 10, 2) -> (5, 10)
U = np.sum(a * b, axis=2) / A
# (5, 10, 1) * (1, 10, 2) = (5, 10, 2)
H = U[:, :, np.newaxis] * a

# (5, 1, 2) - (1, 10, 2) - (5, 10, 2) = (5, 10, 2) -> (5, 10)
dist_on = np.linalg.norm(p[:, np.newaxis, :] - (P0[np.newaxis, :, :] + H), axis=2)
# 始点側
# (5, 1, 2) - (1, 10, 2) = (5, 10, 2) -> (5, 10)
dist_start = np.linalg.norm(p[:, np.newaxis,: ] - P0[np.newaxis, :, :], axis=2)
# 終点側
# (5, 1, 2) - (1, 10, 2) = (5, 10, 2) -> (5, 10)
dist_end = np.linalg.norm(p[:, np.newaxis] - P1[np.newaxis, :, :], axis=2)

# 距離を場合分けで選択
distance = np.where(U < 0, dist_start,
            np.where(U > 1, dist_end, dist_on))
print(distance)


[[19.74586383 18.39392072 11.66317014 11.10821982 15.09707961 14.69617749
  12.96068101  5.82101105  2.72992454  7.19073775]
 [15.77161332 14.09624233  7.73408107  6.77152027 10.8393119  13.8989931
   9.80107975  3.06234643  0.13708207  3.46828548]
 [13.75260675  9.92202968 13.12663559  6.48785875  2.97908782 18.20366037
   6.70812549  9.65619833  7.86787253  8.64289007]
 [ 1.51661847  4.83679375  6.43981238  5.94006873 12.44079777  2.90766306
   4.84600614  6.39090647 14.26716674 11.11814116]
 [ 4.13408903  6.79530968 12.1342682  11.63461892 15.27598942  0.52307228
   9.87458294  9.23068534 18.66912977 16.6064226 ]]


#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
answer(80)

# Author: Nicolas Rougier

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)


In [ ]:

def pad(array, N, i, j, fill=-1):
    out = np.zeros([N, N])
    (row, column) = array.shape
    for a in range(N):
        for b in range(N):
            aa = i - N // 2 + a
            bb = j - N // 2 + b
            if 0 <= aa < row and 0 <= bb < column:
                out[a, b] = array[aa, bb]
            else:
                out[a, b] = fill
    print(out)
            
a = np.arange(16).reshape(4,4)           
pad(a, 3, 0, 0)

[[-1. -1. -1.]
 [-1.  0.  1.]
 [-1.  4.  5.]]


In [ ]:
def get_extract(arr, center, shape, fill=-1):
    out = np.full(shape, fill_value=fill, dtype=arr.dtype)
    arr_shape = np.array(arr.shape)
    shape = np.array(shape)
    center = np.array(center)

    start = center - shape // 2
    end = start + shape 

    arr_start = np.maximum(start, 0)
    arr_end = np.minimum(end, arr_shape)

    out_start = arr_start - start
    out_end = out_start + (arr_end - arr_start)

    out_slices = tuple(slice(s, e) for s, e in zip(out_start, out_end))
    arr_slices = tuple(slice(s, e) for s, e in zip(arr_start, arr_end))
    out[out_slices] = arr[arr_slices]
    print(out)


A = np.arange(16).reshape(4, 4)

get_extract(A, center=(0, 0), shape=(3, 3))

[[-1 -1 -1]
 [-1  0  1]
 [-1  4  5]]


In [ ]:
import numpy as np

def extract_centered_subarray(arr, center, shape, fill=0):
    out = np.full(shape, fill, dtype=arr.dtype)
    arr_shape = np.array(arr.shape)
    shape = np.array(shape)
    center = np.array(center)

    # 元配列と出力配列のスライス範囲を計算
    start = center - shape // 2
    end = center + (shape + 1) // 2

    # 元配列側の有効範囲
    arr_start = np.maximum(start, 0)
    arr_end = np.minimum(end, arr_shape)

    # 出力配列側の有効範囲
    out_start = arr_start - start
    out_end = out_start + (arr_end - arr_start)

    # スライスしてコピー
    out_slices = tuple(slice(s, e) for s, e in zip(out_start, out_end))
    arr_slices = tuple(slice(s, e) for s, e in zip(arr_start, arr_end))
    out[out_start[0]:out_end[0], out_start[1]:out_end[1]] = \
        arr[arr_start[0]:arr_end[0], arr_start[1]:arr_end[1]]
    print(out_slices)
    return out

# 例
a = np.arange(16).reshape(4,4)
print(extract_centered_subarray(a, center=(1, 1), shape=(3, 3), fill=-1))


(slice(0, 3, None), slice(0, 3, None))
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
Z = np.arange(1, 15)
Z = np.lib.stride_tricks.sliding_window_view(Z, 4)
Z

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

In [ ]:
answer(81)

# Author: Stefan van der Walt

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

# Author: Jeff Luo (@Jeff1999)

Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))


#### 82. Compute a matrix rank (★★★)

In [ ]:
A = np.array([[1, 2], [2, 4]])
print(np.linalg.matrix_rank(A))

1


In [ ]:
answer(82)

# Author: Stefan van der Walt

Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

# alternative solution:
# Author: Jeff Luo (@Jeff1999)

rank = np.linalg.matrix_rank(Z)
print(rank)


#### 83. How to find the most frequent value in an array?

In [ ]:
import pandas as pd
A = np.random.randint(0, 10, 20)
A = pd.DataFrame(A)
A.value_counts().reset_index()

0  count
0  0      3
1  2      3
2  5      3
3  9      3
4  1      2
5  3      2
6  7      2
7  4      1
8  6      1

In [ ]:
Z = np.random.randint(0, 10, 20)
# 出現しない値は0としてカウントされる
print(np.bincount(Z))

[0 2 1 5 1 4 5 0 1 1]


In [ ]:
answer(83)

Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [132]:
A = np.arange(0, 100).reshape(10, 10)
A = np.lib.stride_tricks.sliding_window_view(A, (3, 3))
A

array([[[[ 0,  1,  2],
         [10, 11, 12],
         [20, 21, 22]],

        [[ 1,  2,  3],
         [11, 12, 13],
         [21, 22, 23]],

        [[ 2,  3,  4],
         [12, 13, 14],
         [22, 23, 24]],

        [[ 3,  4,  5],
         [13, 14, 15],
         [23, 24, 25]],

        [[ 4,  5,  6],
         [14, 15, 16],
         [24, 25, 26]],

        [[ 5,  6,  7],
         [15, 16, 17],
         [25, 26, 27]],

        [[ 6,  7,  8],
         [16, 17, 18],
         [26, 27, 28]],

        [[ 7,  8,  9],
         [17, 18, 19],
         [27, 28, 29]]],


       [[[10, 11, 12],
         [20, 21, 22],
         [30, 31, 32]],

        [[11, 12, 13],
         [21, 22, 23],
         [31, 32, 33]],

        [[12, 13, 14],
         [22, 23, 24],
         [32, 33, 34]],

        [[13, 14, 15],
         [23, 24, 25],
         [33, 34, 35]],

        [[14, 15, 16],
         [24, 25, 26],
         [34, 35, 36]],

        [[15, 16, 17],
         [25, 26, 27],
         [35, 36, 37]],

    

In [133]:
answer(84)

# Author: Chris Barker

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

# Author: Jeff Luo (@Jeff1999)

Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)