# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [210]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [211]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [212]:
print(np.__version__)

1.26.4


#### 3. Create a null vector of size 10 (★☆☆)

In [213]:
a = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [214]:
a.nbytes
answer(4)

Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [215]:
# help(np.add)
answer(5)

%run `python -c "import numpy; numpy.info(numpy.add)"`


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [216]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [217]:
answer(6)

Z = np.zeros(10)
Z[4] = 1
print(Z)


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [218]:
a = np.random.randint(10, 50, 10)
a


array([14, 35, 48, 37, 29, 24, 43, 42, 41, 14])

In [219]:
answer(7)

Z = np.arange(10,50)
print(Z)


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [220]:
a[::-1]

array([14, 41, 42, 43, 24, 29, 37, 48, 35, 14])

In [221]:
answer(8)

Z = np.arange(50)
Z = Z[::-1]
print(Z)


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [222]:
a = np.random.randint(0, 9, 9).reshape(3, 3)
a

array([[5, 2, 4],
       [3, 5, 2],
       [2, 5, 2]])

In [223]:
answer(9)

Z = np.arange(9).reshape(3, 3)
print(Z)


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [224]:
a = np.array([1, 2, 0, 0, 4, 0])
a = np.where(a == 0)
a

(array([2, 3, 5], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [225]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [226]:
np.random.random([3, 3, 3])

array([[[0.29506771, 0.02653551, 0.6935116 ],
        [0.77266485, 0.01608925, 0.65453651],
        [0.05227418, 0.67756457, 0.50925169]],

       [[0.50265842, 0.58024973, 0.04016008],
        [0.2172174 , 0.07801214, 0.46661273],
        [0.60718134, 0.80252978, 0.40007419]],

       [[0.5194413 , 0.64568992, 0.89991591],
        [0.41241163, 0.57399776, 0.88269304],
        [0.61670483, 0.48845073, 0.93708198]]])

In [227]:
answer(12)

Z = np.random.random((3,3,3))
print(Z)


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [228]:
a = np.random.random([10, 10])
print(a.min(), a.max())

0.009517814449151119 0.9631509363281929


In [229]:
answer(13)

Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [230]:
a = np.random.random(30).mean()
print(a)

0.4483495343049349


In [231]:
answer(14)

Z = np.random.random(30)
m = Z.mean()
print(m)


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [232]:
a = np.ones([4, 4])
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [233]:
answer(15)

Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [234]:
a = np.ones([3, 3])
a = np.pad(a, pad_width=1, mode="constant")  # padding
a

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [235]:
answer(16)

Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [236]:
0.3 == 3 * 0.1

False

In [237]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [238]:
answer(17)

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [239]:
np.diag([1, 2, 3, 4], k=0)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [240]:
a = np.zeros([8, 8])
a[::2, ::2] = 1
a[1::2, 1::2] = 1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [241]:
a = np.array(np.arange(336).reshape(6, 7, 8))
a[1, 5, 3]

99

In [242]:
print(np.unravel_index(99,(6,7,8)))  # 1次元のインデックスを多次元インデックスに変換してくれる

(1, 5, 3)


In [243]:
answer(20)

print(np.unravel_index(99,(6,7,8)))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [244]:
a = [[0, 1], [1, 0]]
b = np.tile(a, (4, 4))
b

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [245]:
answer(21)

Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [246]:
a = np.array(np.random.random((5, 5)))
a_min = a.min()
a_max = a.max()
a = (a - a_min) / (a_max - a_min)
a


array([[0.56525962, 0.92223299, 0.02492735, 0.17832914, 0.41504679],
       [0.96161013, 0.78755665, 0.96520924, 0.37662768, 0.88612138],
       [0.3034454 , 0.        , 0.34329541, 0.99942011, 0.85940879],
       [0.4946843 , 0.46275114, 0.7372982 , 0.64107428, 0.44028214],
       [1.        , 0.9003088 , 0.16074645, 0.80518237, 0.24889442]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [247]:
color = np.dtype([("r", np.ubyte),
                 ("g", np.ubyte),
                 ("b", np.ubyte),
                 ("a", np.ubyte)])

In [248]:
answer(23)

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [249]:
a = np.array(np.random.random([5, 3]))
b = np.array(np.random.random([3, 2]))
np.matmul(a, b)

array([[0.41700254, 0.33838302],
       [0.97670421, 1.05951266],
       [0.6724485 , 0.61473336],
       [0.20206762, 0.22311153],
       [0.70662596, 0.62427151]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [250]:
a = np.array(np.arange(11))
a[((3 < a) & (a < 8))] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

In [251]:
answer(25)

# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)


In [252]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [253]:
sum(range(5), -1)

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [254]:
####
"""python
1. ok
2. no
3. ok
4. ok
5. ok
6. no
"""

'python\n1. ok\n2. no\n3. ok\n4. ok\n5. ok\n6. no\n'

In [255]:
Z = np.array([1, 2, 3])
1j*Z  # jは虚数単位

array([0.+1.j, 0.+2.j, 0.+3.j])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [256]:
np.array(0) / np.array(0)  # numpyはエラーが出たときに中断せずに、nanを返す

C:\Users\CHU1P\AppData\Local\Temp\ipykernel_34940\941235769.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)  # numpyはエラーが出たときに中断せずに、nanを返す


nan

In [257]:
np.array(0) // np.array(0)

C:\Users\CHU1P\AppData\Local\Temp\ipykernel_34940\2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [258]:
np.array([np.nan]).astype(int).astype(float)  # np.nanはint型に変えるとその方の最小値になる

C:\Users\CHU1P\AppData\Local\Temp\ipykernel_34940\2424127791.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)  # np.nanはint型に変えるとその方の最小値になる


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [259]:
a = np.array(np.random.uniform(-10, 10, 5))
print(a)
a = np.where(a >= 0, np.ceil(a), np.floor(a))
print(a)

[ 2.73868478 -2.58073289  3.12670131  9.97265213 -8.08572041]
[ 3. -3.  4. 10. -9.]


In [260]:
answer(29)

# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
a = np.random.randint(1, 9, 5)
b = np.random.randint(1, 9, 5)
print(a, b)
np.intersect1d(a, b)  # 共通の値を出力する, 出力はsortされている

[4 6 7 7 2] [3 5 2 4 4]


array([2, 4])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [265]:
answer(31)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


In [ ]:
defaults = np.seterr(all="ignore")
z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.emath.sqrt(-1)  # emathは複素数が答えの場合は複素数に変える

1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [276]:
print(np.datetime64("today", "D") - np.timedelta64(1, "D"))
print(np.datetime64("today", "D"))
print(np.datetime64("today", "D") + np.timedelta64(1, "D"))

2025-06-15
2025-06-16
2025-06-17


In [291]:
import pandas as pd

today = pd.Timestamp("today")
yesterday = (today - pd.Timedelta(days=1)).strftime("%Y-%m-%d")
tomorrow = (today + pd.Timedelta(days=1)).strftime("%Y-%m-%d")
today = today.strftime("%Y-%m-%d")
print(yesterday, today, tomorrow)

2025-06-15 2025-06-16 2025-06-17


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [298]:
a = pd.date_range(start="2016-07-01", end="2016-07-31", freq="D")
a

DatetimeIndex(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
               '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
               '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
               '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
               '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
               '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
               '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
               '2016-07-29', '2016-07-30', '2016-07-31'],
              dtype='datetime64[ns]', freq='D')

In [295]:
np.arange("2016-07", "2016-08", dtype="datetime64[D]")

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [292]:
answer(34)

Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)